// ============================================================
// _generic_registry.ts — Session 19+20 bulk spell dispatch registry
//
// This file is AUTO-GENERATED by /home/z/my-project/workspace/scripts/
// generate_integration.py + generate_l1_integration.py. Do not edit by
// hand — re-run the script after adding/removing spells from the bulk
// implementation.
//
// Purpose: provides a single dispatch point for the bulk-implemented
// spells (Session 19: 262 L2-9 spells + Session 20: 51 L1 spells = 313
// total). combat.ts's `case 'genericSpell':` branch and planner.ts's
// generic-spell loop both import from this file.
//
// Each spell is imported individually and registered in the GENERIC_SPELLS
// map keyed by canonical spell name. The map value is a tuple of
// { shouldCast, execute, level } — enough for both the engine (execute)
// and the planner (shouldCast + level for slot gating).
// ============================================================

// ---- Imports — one per spell module -------------------------

import {
  shouldCast as shouldCastAlarm,
  execute as executeAlarm,
  metadata as metadataAlarm,
} from './alarm';

import {
  shouldCast as shouldCastAnimalFriendship,
  execute as executeAnimalFriendship,
  metadata as metadataAnimalFriendship,
} from './animal_friendship';

import {
  shouldCast as shouldCastArmorOfAgathys,
  execute as executeArmorOfAgathys,
  metadata as metadataArmorOfAgathys,
} from './armor_of_agathys';

import {
  shouldCast as shouldCastBane,
  execute as executeBane,
  metadata as metadataBane,
} from './bane';

import {
  shouldCast as shouldCastBeastBond,
  execute as executeBeastBond,
  metadata as metadataBeastBond,
} from './beast_bond';

import {
  shouldCast as shouldCastCauseFear,
  execute as executeCauseFear,
  metadata as metadataCauseFear,
} from './cause_fear';

import {
  shouldCast as shouldCastCeremony,
  execute as executeCeremony,
  metadata as metadataCeremony,
} from './ceremony';

import {
  shouldCast as shouldCastCharmPerson,
  execute as executeCharmPerson,
  metadata as metadataCharmPerson,
} from './charm_person';

import {
  shouldCast as shouldCastColorSpray,
  execute as executeColorSpray,
  metadata as metadataColorSpray,
} from './color_spray';

import {
  shouldCast as shouldCastCommand,
  execute as executeCommand,
  metadata as metadataCommand,
} from './command';

import {
  shouldCast as shouldCastCompelledDuel,
  execute as executeCompelledDuel,
  metadata as metadataCompelledDuel,
} from './compelled_duel';

import {
  shouldCast as shouldCastCreateOrDestroyWater,
  execute as executeCreateOrDestroyWater,
  metadata as metadataCreateOrDestroyWater,
} from './create_or_destroy_water';

import {
  shouldCast as shouldCastDisguiseSelf,
  execute as executeDisguiseSelf,
  metadata as metadataDisguiseSelf,
} from './disguise_self';

import {
  shouldCast as shouldCastDistortValue,
  execute as executeDistortValue,
  metadata as metadataDistortValue,
} from './distort_value';

import {
  shouldCast as shouldCastDivineFavor,
  execute as executeDivineFavor,
  metadata as metadataDivineFavor,
} from './divine_favor';

import {
  shouldCast as shouldCastEnsnaringStrike,
  execute as executeEnsnaringStrike,
  metadata as metadataEnsnaringStrike,
} from './ensnaring_strike';

import {
  shouldCast as shouldCastExpeditiousRetreat,
  execute as executeExpeditiousRetreat,
  metadata as metadataExpeditiousRetreat,
} from './expeditious_retreat';

import {
  shouldCast as shouldCastFalseLife,
  execute as executeFalseLife,
  metadata as metadataFalseLife,
} from './false_life';

import {
  shouldCast as shouldCastGiftOfAlacrity,
  execute as executeGiftOfAlacrity,
  metadata as metadataGiftOfAlacrity,
} from './gift_of_alacrity';

import {
  shouldCast as shouldCastGoodberry,
  execute as executeGoodberry,
  metadata as metadataGoodberry,
} from './goodberry';

import {
  shouldCast as shouldCastGrease,
  execute as executeGrease,
  metadata as metadataGrease,
} from './grease';

import {
  shouldCast as shouldCastHailOfThorns,
  execute as executeHailOfThorns,
  metadata as metadataHailOfThorns,
} from './hail_of_thorns';

import {
  shouldCast as shouldCastHeroism,
  execute as executeHeroism,
  metadata as metadataHeroism,
} from './heroism';

import {
  shouldCast as shouldCastHuntersMark,
  execute as executeHuntersMark,
  metadata as metadataHuntersMark,
} from './hunters_mark';

import {
  shouldCast as shouldCastJimsMagicMissile,
  execute as executeJimsMagicMissile,
  metadata as metadataJimsMagicMissile,
} from './jims_magic_missile';

import {
  shouldCast as shouldCastJump,
  execute as executeJump,
  metadata as metadataJump,
} from './jump';

import {
  shouldCast as shouldCastPurifyFoodAndDrink,
  execute as executePurifyFoodAndDrink,
  metadata as metadataPurifyFoodAndDrink,
} from './purify_food_and_drink';

import {
  shouldCast as shouldCastSanctuary,
  execute as executeSanctuary,
  metadata as metadataSanctuary,
} from './sanctuary';

import {
  shouldCast as shouldCastSearingSmite,
  execute as executeSearingSmite,
  metadata as metadataSearingSmite,
} from './searing_smite';

import {
  shouldCast as shouldCastSilentImage,
  execute as executeSilentImage,
  metadata as metadataSilentImage,
} from './silent_image';

import {
  shouldCast as shouldCastSnare,
  execute as executeSnare,
  metadata as metadataSnare,
} from './snare';

import {
  shouldCast as shouldCastSpeakWithAnimals,
  execute as executeSpeakWithAnimals,
  metadata as metadataSpeakWithAnimals,
} from './speak_with_animals';

import {
  shouldCast as shouldCastTashasCausticBrew,
  execute as executeTashasCausticBrew,
  metadata as metadataTashasCausticBrew,
} from './tashas_caustic_brew';

import {
  shouldCast as shouldCastTashasHideousLaughter,
  execute as executeTashasHideousLaughter,
  metadata as metadataTashasHideousLaughter,
} from './tashas_hideous_laughter';

import {
  shouldCast as shouldCastTensersFloatingDisk,
  execute as executeTensersFloatingDisk,
  metadata as metadataTensersFloatingDisk,
} from './tensers_floating_disk';

import {
  shouldCast as shouldCastThunderousSmite,
  execute as executeThunderousSmite,
  metadata as metadataThunderousSmite,
} from './thunderous_smite';

import {
  shouldCast as shouldCastUnseenServant,
  execute as executeUnseenServant,
  metadata as metadataUnseenServant,
} from './unseen_servant';

import {
  shouldCast as shouldCastWrathfulSmite,
  execute as executeWrathfulSmite,
  metadata as metadataWrathfulSmite,
} from './wrathful_smite';

import {
  shouldCast as shouldCastZephyrStrike,
  execute as executeZephyrStrike,
  metadata as metadataZephyrStrike,
} from './zephyr_strike';

import {
  shouldCast as shouldCastAganazzarsScorcher,
  execute as executeAganazzarsScorcher,
  metadata as metadataAganazzarsScorcher,
} from './aganazzars_scorcher';

import {
  shouldCast as shouldCastAirBubble,
  execute as executeAirBubble,
  metadata as metadataAirBubble,
} from './air_bubble';

import {
  shouldCast as shouldCastAnimalMessenger,
  execute as executeAnimalMessenger,
  metadata as metadataAnimalMessenger,
} from './animal_messenger';

import {
  shouldCast as shouldCastBeastSense,
  execute as executeBeastSense,
  metadata as metadataBeastSense,
} from './beast_sense';

import {
  shouldCast as shouldCastBorrowedKnowledge,
  execute as executeBorrowedKnowledge,
  metadata as metadataBorrowedKnowledge,
} from './borrowed_knowledge';

import {
  shouldCast as shouldCastContinualFlame,
  execute as executeContinualFlame,
  metadata as metadataContinualFlame,
} from './continual_flame';

import {
  shouldCast as shouldCastDeathArmor,
  execute as executeDeathArmor,
  metadata as metadataDeathArmor,
} from './death_armor';

import {
  shouldCast as shouldCastDeryansHelpfulHomunculi,
  execute as executeDeryansHelpfulHomunculi,
  metadata as metadataDeryansHelpfulHomunculi,
} from './deryans_helpful_homunculi';

import {
  shouldCast as shouldCastDragonsBreath,
  execute as executeDragonsBreath,
  metadata as metadataDragonsBreath,
} from './dragons_breath';

import {
  shouldCast as shouldCastDustDevil,
  execute as executeDustDevil,
  metadata as metadataDustDevil,
} from './dust_devil';

import {
  shouldCast as shouldCastEarthbind,
  execute as executeEarthbind,
  metadata as metadataEarthbind,
} from './earthbind';

import {
  shouldCast as shouldCastElminstersElusion,
  execute as executeElminstersElusion,
  metadata as metadataElminstersElusion,
} from './elminsters_elusion';

import {
  shouldCast as shouldCastFindTraps,
  execute as executeFindTraps,
  metadata as metadataFindTraps,
} from './find_traps';

import {
  shouldCast as shouldCastFlockOfFamiliars,
  execute as executeFlockOfFamiliars,
  metadata as metadataFlockOfFamiliars,
} from './flock_of_familiars';

import {
  shouldCast as shouldCastFortunesFavor,
  execute as executeFortunesFavor,
  metadata as metadataFortunesFavor,
} from './fortunes_favor';

import {
  shouldCast as shouldCastGiftOfGab,
  execute as executeGiftOfGab,
  metadata as metadataGiftOfGab,
} from './gift_of_gab';

import {
  shouldCast as shouldCastHealingSpirit,
  execute as executeHealingSpirit,
  metadata as metadataHealingSpirit,
} from './healing_spirit';

import {
  shouldCast as shouldCastHomunculusServant,
  execute as executeHomunculusServant,
  metadata as metadataHomunculusServant,
} from './homunculus_servant';

import {
  shouldCast as shouldCastImmovableObject,
  execute as executeImmovableObject,
  metadata as metadataImmovableObject,
} from './immovable_object';

import {
  shouldCast as shouldCastJimsGlowingCoin,
  execute as executeJimsGlowingCoin,
  metadata as metadataJimsGlowingCoin,
} from './jims_glowing_coin';

import {
  shouldCast as shouldCastKineticJaunt,
  execute as executeKineticJaunt,
  metadata as metadataKineticJaunt,
} from './kinetic_jaunt';

import {
  shouldCast as shouldCastMagicMouth,
  execute as executeMagicMouth,
  metadata as metadataMagicMouth,
} from './magic_mouth';

import {
  shouldCast as shouldCastMaximiliansEarthenGrasp,
  execute as executeMaximiliansEarthenGrasp,
  metadata as metadataMaximiliansEarthenGrasp,
} from './maximilians_earthen_grasp';

import {
  shouldCast as shouldCastNathairsMischief,
  execute as executeNathairsMischief,
  metadata as metadataNathairsMischief,
} from './nathairs_mischief';

import {
  shouldCast as shouldCastNystulsMagicAura,
  execute as executeNystulsMagicAura,
  metadata as metadataNystulsMagicAura,
} from './nystuls_magic_aura';

import {
  shouldCast as shouldCastPyrotechnics,
  execute as executePyrotechnics,
  metadata as metadataPyrotechnics,
} from './pyrotechnics';

import {
  shouldCast as shouldCastRimesBindingIce,
  execute as executeRimesBindingIce,
  metadata as metadataRimesBindingIce,
} from './rimes_binding_ice';

import {
  shouldCast as shouldCastShadowBlade,
  execute as executeShadowBlade,
  metadata as metadataShadowBlade,
} from './shadow_blade';

import {
  shouldCast as shouldCastSkywrite,
  execute as executeSkywrite,
  metadata as metadataSkywrite,
} from './skywrite';

import {
  shouldCast as shouldCastSnillocsSnowballSwarm,
  execute as executeSnillocsSnowballSwarm,
  metadata as metadataSnillocsSnowballSwarm,
} from './snillocs_snowball_swarm';

import {
  shouldCast as shouldCastTashasMindWhip,
  execute as executeTashasMindWhip,
  metadata as metadataTashasMindWhip,
} from './tashas_mind_whip';

import {
  shouldCast as shouldCastVortexWarp,
  execute as executeVortexWarp,
  metadata as metadataVortexWarp,
} from './vortex_warp';

import {
  shouldCast as shouldCastWardingWind,
  execute as executeWardingWind,
  metadata as metadataWardingWind,
} from './warding_wind';

import {
  shouldCast as shouldCastWarpSense,
  execute as executeWarpSense,
  metadata as metadataWarpSense,
} from './warp_sense';

import {
  shouldCast as shouldCastWitherAndBloom,
  execute as executeWitherAndBloom,
  metadata as metadataWitherAndBloom,
} from './wither_and_bloom';

import {
  shouldCast as shouldCastWristpocket,
  execute as executeWristpocket,
  metadata as metadataWristpocket,
} from './wristpocket';

import {
  shouldCast as shouldCastAntagonize,
  execute as executeAntagonize,
  metadata as metadataAntagonize,
} from './antagonize';

import {
  shouldCast as shouldCastAshardalonsStride,
  execute as executeAshardalonsStride,
  metadata as metadataAshardalonsStride,
} from './ashardalons_stride';

import {
  shouldCast as shouldCastAuraOfVitality,
  execute as executeAuraOfVitality,
  metadata as metadataAuraOfVitality,
} from './aura_of_vitality';

import {
  shouldCast as shouldCastBeaconOfHope,
  execute as executeBeaconOfHope,
  metadata as metadataBeaconOfHope,
} from './beacon_of_hope';

import {
  shouldCast as shouldCastBestowCurse,
  execute as executeBestowCurse,
  metadata as metadataBestowCurse,
} from './bestow_curse';

import {
  shouldCast as shouldCastBlindingSmite,
  execute as executeBlindingSmite,
  metadata as metadataBlindingSmite,
} from './blinding_smite';

import {
  shouldCast as shouldCastBlink,
  execute as executeBlink,
  metadata as metadataBlink,
} from './blink';

import {
  shouldCast as shouldCastCacophonicShield,
  execute as executeCacophonicShield,
  metadata as metadataCacophonicShield,
} from './cacophonic_shield';

import {
  shouldCast as shouldCastCallLightning,
  execute as executeCallLightning,
  metadata as metadataCallLightning,
} from './call_lightning';

import {
  shouldCast as shouldCastCatnap,
  execute as executeCatnap,
  metadata as metadataCatnap,
} from './catnap';

import {
  shouldCast as shouldCastCreateFoodAndWater,
  execute as executeCreateFoodAndWater,
  metadata as metadataCreateFoodAndWater,
} from './create_food_and_water';

import {
  shouldCast as shouldCastCrusadersMantle,
  execute as executeCrusadersMantle,
  metadata as metadataCrusadersMantle,
} from './crusaders_mantle';

import {
  shouldCast as shouldCastDaylight,
  execute as executeDaylight,
  metadata as metadataDaylight,
} from './daylight';

import {
  shouldCast as shouldCastElementalWeapon,
  execute as executeElementalWeapon,
  metadata as metadataElementalWeapon,
} from './elemental_weapon';

import {
  shouldCast as shouldCastEnemiesAbound,
  execute as executeEnemiesAbound,
  metadata as metadataEnemiesAbound,
} from './enemies_abound';

import {
  shouldCast as shouldCastEruptingEarth,
  execute as executeEruptingEarth,
  metadata as metadataEruptingEarth,
} from './erupting_earth';

import {
  shouldCast as shouldCastFastFriends,
  execute as executeFastFriends,
  metadata as metadataFastFriends,
} from './fast_friends';

import {
  shouldCast as shouldCastFear,
  execute as executeFear,
  metadata as metadataFear,
} from './fear';

import {
  shouldCast as shouldCastFeignDeath,
  execute as executeFeignDeath,
  metadata as metadataFeignDeath,
} from './feign_death';

import {
  shouldCast as shouldCastFlameArrows,
  execute as executeFlameArrows,
  metadata as metadataFlameArrows,
} from './flame_arrows';

import {
  shouldCast as shouldCastFly,
  execute as executeFly,
  metadata as metadataFly,
} from './fly';

import {
  shouldCast as shouldCastGaldersTower,
  execute as executeGaldersTower,
  metadata as metadataGaldersTower,
} from './galders_tower';

import {
  shouldCast as shouldCastGaseousForm,
  execute as executeGaseousForm,
  metadata as metadataGaseousForm,
} from './gaseous_form';

import {
  shouldCast as shouldCastHaste,
  execute as executeHaste,
  metadata as metadataHaste,
} from './haste';

import {
  shouldCast as shouldCastHungerOfHadar,
  execute as executeHungerOfHadar,
  metadata as metadataHungerOfHadar,
} from './hunger_of_hadar';

import {
  shouldCast as shouldCastHypnoticPattern,
  execute as executeHypnoticPattern,
  metadata as metadataHypnoticPattern,
} from './hypnotic_pattern';

import {
  shouldCast as shouldCastInciteGreed,
  execute as executeInciteGreed,
  metadata as metadataInciteGreed,
} from './incite_greed';

import {
  shouldCast as shouldCastIntellectFortress,
  execute as executeIntellectFortress,
  metadata as metadataIntellectFortress,
} from './intellect_fortress';

import {
  shouldCast as shouldCastLaeralsSilverLance,
  execute as executeLaeralsSilverLance,
  metadata as metadataLaeralsSilverLance,
} from './laerals_silver_lance';

import {
  shouldCast as shouldCastLeomundsTinyHut,
  execute as executeLeomundsTinyHut,
  metadata as metadataLeomundsTinyHut,
} from './leomunds_tiny_hut';

import {
  shouldCast as shouldCastLifeTransference,
  execute as executeLifeTransference,
  metadata as metadataLifeTransference,
} from './life_transference';

import {
  shouldCast as shouldCastLightningArrow,
  execute as executeLightningArrow,
  metadata as metadataLightningArrow,
} from './lightning_arrow';

import {
  shouldCast as shouldCastLinkedGlyphs,
  execute as executeLinkedGlyphs,
  metadata as metadataLinkedGlyphs,
} from './linked_glyphs';

import {
  shouldCast as shouldCastMajorImage,
  execute as executeMajorImage,
  metadata as metadataMajorImage,
} from './major_image';

import {
  shouldCast as shouldCastMassHealingWord,
  execute as executeMassHealingWord,
  metadata as metadataMassHealingWord,
} from './mass_healing_word';

import {
  shouldCast as shouldCastMeldIntoStone,
  execute as executeMeldIntoStone,
  metadata as metadataMeldIntoStone,
} from './meld_into_stone';

import {
  shouldCast as shouldCastMelfsMinuteMeteors,
  execute as executeMelfsMinuteMeteors,
  metadata as metadataMelfsMinuteMeteors,
} from './melfs_minute_meteors';

import {
  shouldCast as shouldCastMotivationalSpeech,
  execute as executeMotivationalSpeech,
  metadata as metadataMotivationalSpeech,
} from './motivational_speech';

import {
  shouldCast as shouldCastNondetection,
  execute as executeNondetection,
  metadata as metadataNondetection,
} from './nondetection';

import {
  shouldCast as shouldCastPhantomSteed,
  execute as executePhantomSteed,
  metadata as metadataPhantomSteed,
} from './phantom_steed';

import {
  shouldCast as shouldCastPlantGrowth,
  execute as executePlantGrowth,
  metadata as metadataPlantGrowth,
} from './plant_growth';

import {
  shouldCast as shouldCastPulseWave,
  execute as executePulseWave,
  metadata as metadataPulseWave,
} from './pulse_wave';

import {
  shouldCast as shouldCastRemoveCurse,
  execute as executeRemoveCurse,
  metadata as metadataRemoveCurse,
} from './remove_curse';

import {
  shouldCast as shouldCastSleetStorm,
  execute as executeSleetStorm,
  metadata as metadataSleetStorm,
} from './sleet_storm';

import {
  shouldCast as shouldCastSlow,
  execute as executeSlow,
  metadata as metadataSlow,
} from './slow';

import {
  shouldCast as shouldCastSpeakWithDead,
  execute as executeSpeakWithDead,
  metadata as metadataSpeakWithDead,
} from './speak_with_dead';

import {
  shouldCast as shouldCastSpeakWithPlants,
  execute as executeSpeakWithPlants,
  metadata as metadataSpeakWithPlants,
} from './speak_with_plants';

import {
  shouldCast as shouldCastSpiritGuardians,
  execute as executeSpiritGuardians,
  metadata as metadataSpiritGuardians,
} from './spirit_guardians';

import {
  shouldCast as shouldCastSpiritShroud,
  execute as executeSpiritShroud,
  metadata as metadataSpiritShroud,
} from './spirit_shroud';

import {
  shouldCast as shouldCastStinkingCloud,
  execute as executeStinkingCloud,
  metadata as metadataStinkingCloud,
} from './stinking_cloud';

import {
  shouldCast as shouldCastSylunésViper,
  execute as executeSylunésViper,
  metadata as metadataSylunésViper,
} from './sylunés_viper';

import {
  shouldCast as shouldCastTidalWave,
  execute as executeTidalWave,
  metadata as metadataTidalWave,
} from './tidal_wave';

import {
  shouldCast as shouldCastTinyServant,
  execute as executeTinyServant,
  metadata as metadataTinyServant,
} from './tiny_servant';

import {
  shouldCast as shouldCastVampiricTouch,
  execute as executeVampiricTouch,
  metadata as metadataVampiricTouch,
} from './vampiric_touch';

import {
  shouldCast as shouldCastAuraOfLife,
  execute as executeAuraOfLife,
  metadata as metadataAuraOfLife,
} from './aura_of_life';

import {
  shouldCast as shouldCastAuraOfPurity,
  execute as executeAuraOfPurity,
  metadata as metadataAuraOfPurity,
} from './aura_of_purity';

import {
  shouldCast as shouldCastBacklash,
  execute as executeBacklash,
  metadata as metadataBacklash,
} from './backlash';

import {
  shouldCast as shouldCastCharmMonster,
  execute as executeCharmMonster,
  metadata as metadataCharmMonster,
} from './charm_monster';

import {
  shouldCast as shouldCastCompulsion,
  execute as executeCompulsion,
  metadata as metadataCompulsion,
} from './compulsion';

import {
  shouldCast as shouldCastConfusion,
  execute as executeConfusion,
  metadata as metadataConfusion,
} from './confusion';

import {
  shouldCast as shouldCastControlWater,
  execute as executeControlWater,
  metadata as metadataControlWater,
} from './control_water';

import {
  shouldCast as shouldCastDeathWard,
  execute as executeDeathWard,
  metadata as metadataDeathWard,
} from './death_ward';

import {
  shouldCast as shouldCastDominateBeast,
  execute as executeDominateBeast,
  metadata as metadataDominateBeast,
} from './dominate_beast';

import {
  shouldCast as shouldCastDoomtide,
  execute as executeDoomtide,
  metadata as metadataDoomtide,
} from './doomtide';

import {
  shouldCast as shouldCastElementalBane,
  execute as executeElementalBane,
  metadata as metadataElementalBane,
} from './elemental_bane';

import {
  shouldCast as shouldCastEvardsBlackTentacles,
  execute as executeEvardsBlackTentacles,
  metadata as metadataEvardsBlackTentacles,
} from './evards_black_tentacles';

import {
  shouldCast as shouldCastFabricate,
  execute as executeFabricate,
  metadata as metadataFabricate,
} from './fabricate';

import {
  shouldCast as shouldCastFireShield,
  execute as executeFireShield,
  metadata as metadataFireShield,
} from './fire_shield';

import {
  shouldCast as shouldCastFreedomOfMovement,
  execute as executeFreedomOfMovement,
  metadata as metadataFreedomOfMovement,
} from './freedom_of_movement';

import {
  shouldCast as shouldCastGaldersSpeedyCourier,
  execute as executeGaldersSpeedyCourier,
  metadata as metadataGaldersSpeedyCourier,
} from './galders_speedy_courier';

import {
  shouldCast as shouldCastGateSeal,
  execute as executeGateSeal,
  metadata as metadataGateSeal,
} from './gate_seal';

import {
  shouldCast as shouldCastGiantInsect,
  execute as executeGiantInsect,
  metadata as metadataGiantInsect,
} from './giant_insect';

import {
  shouldCast as shouldCastGraspingVine,
  execute as executeGraspingVine,
  metadata as metadataGraspingVine,
} from './grasping_vine';

import {
  shouldCast as shouldCastGravitySinkhole,
  execute as executeGravitySinkhole,
  metadata as metadataGravitySinkhole,
} from './gravity_sinkhole';

import {
  shouldCast as shouldCastGuardianOfFaith,
  execute as executeGuardianOfFaith,
  metadata as metadataGuardianOfFaith,
} from './guardian_of_faith';

import {
  shouldCast as shouldCastGuardianOfNature,
  execute as executeGuardianOfNature,
  metadata as metadataGuardianOfNature,
} from './guardian_of_nature';

import {
  shouldCast as shouldCastHallucinatoryTerrain,
  execute as executeHallucinatoryTerrain,
  metadata as metadataHallucinatoryTerrain,
} from './hallucinatory_terrain';

import {
  shouldCast as shouldCastIceStorm,
  execute as executeIceStorm,
  metadata as metadataIceStorm,
} from './ice_storm';

import {
  shouldCast as shouldCastMordenkainensFaithfulHound,
  execute as executeMordenkainensFaithfulHound,
  metadata as metadataMordenkainensFaithfulHound,
} from './mordenkainens_faithful_hound';

import {
  shouldCast as shouldCastMordenkainensPrivateSanctum,
  execute as executeMordenkainensPrivateSanctum,
  metadata as metadataMordenkainensPrivateSanctum,
} from './mordenkainens_private_sanctum';

import {
  shouldCast as shouldCastOtilukesResilientSphere,
  execute as executeOtilukesResilientSphere,
  metadata as metadataOtilukesResilientSphere,
} from './otilukes_resilient_sphere';

import {
  shouldCast as shouldCastPhantasmalKiller,
  execute as executePhantasmalKiller,
  metadata as metadataPhantasmalKiller,
} from './phantasmal_killer';

import {
  shouldCast as shouldCastPolymorph,
  execute as executePolymorph,
  metadata as metadataPolymorph,
} from './polymorph';

import {
  shouldCast as shouldCastRaulothimsPsychicLance,
  execute as executeRaulothimsPsychicLance,
  metadata as metadataRaulothimsPsychicLance,
} from './raulothims_psychic_lance';

import {
  shouldCast as shouldCastShadowOfMoil,
  execute as executeShadowOfMoil,
  metadata as metadataShadowOfMoil,
} from './shadow_of_moil';

import {
  shouldCast as shouldCastSickeningRadiance,
  execute as executeSickeningRadiance,
  metadata as metadataSickeningRadiance,
} from './sickening_radiance';

import {
  shouldCast as shouldCastSpellfireStorm,
  execute as executeSpellfireStorm,
  metadata as metadataSpellfireStorm,
} from './spellfire_storm';

import {
  shouldCast as shouldCastSpiritOfDeath,
  execute as executeSpiritOfDeath,
  metadata as metadataSpiritOfDeath,
} from './spirit_of_death';

import {
  shouldCast as shouldCastStaggeringSmite,
  execute as executeStaggeringSmite,
  metadata as metadataStaggeringSmite,
} from './staggering_smite';

import {
  shouldCast as shouldCastStoneShape,
  execute as executeStoneShape,
  metadata as metadataStoneShape,
} from './stone_shape';

import {
  shouldCast as shouldCastStoneskin,
  execute as executeStoneskin,
  metadata as metadataStoneskin,
} from './stoneskin';

import {
  shouldCast as shouldCastStormSphere,
  execute as executeStormSphere,
  metadata as metadataStormSphere,
} from './storm_sphere';

import {
  shouldCast as shouldCastVitriolicSphere,
  execute as executeVitriolicSphere,
  metadata as metadataVitriolicSphere,
} from './vitriolic_sphere';

import {
  shouldCast as shouldCastWaterySphere,
  execute as executeWaterySphere,
  metadata as metadataWaterySphere,
} from './watery_sphere';

import {
  shouldCast as shouldCastAlustrielsMooncloak,
  execute as executeAlustrielsMooncloak,
  metadata as metadataAlustrielsMooncloak,
} from './alustriels_mooncloak';

import {
  shouldCast as shouldCastAnimateObjects,
  execute as executeAnimateObjects,
  metadata as metadataAnimateObjects,
} from './animate_objects';

import {
  shouldCast as shouldCastAntilifeShell,
  execute as executeAntilifeShell,
  metadata as metadataAntilifeShell,
} from './antilife_shell';

import {
  shouldCast as shouldCastBanishingSmite,
  execute as executeBanishingSmite,
  metadata as metadataBanishingSmite,
} from './banishing_smite';

import {
  shouldCast as shouldCastBigbysHand,
  execute as executeBigbysHand,
  metadata as metadataBigbysHand,
} from './bigbys_hand';

import {
  shouldCast as shouldCastCircleOfPower,
  execute as executeCircleOfPower,
  metadata as metadataCircleOfPower,
} from './circle_of_power';

import {
  shouldCast as shouldCastCommuneWithNature,
  execute as executeCommuneWithNature,
  metadata as metadataCommuneWithNature,
} from './commune_with_nature';

import {
  shouldCast as shouldCastContagion,
  execute as executeContagion,
  metadata as metadataContagion,
} from './contagion';

import {
  shouldCast as shouldCastControlWinds,
  execute as executeControlWinds,
  metadata as metadataControlWinds,
} from './control_winds';

import {
  shouldCast as shouldCastCreateSpelljammingHelm,
  execute as executeCreateSpelljammingHelm,
  metadata as metadataCreateSpelljammingHelm,
} from './create_spelljamming_helm';

import {
  shouldCast as shouldCastCreation,
  execute as executeCreation,
  metadata as metadataCreation,
} from './creation';

import {
  shouldCast as shouldCastDanseMacabre,
  execute as executeDanseMacabre,
  metadata as metadataDanseMacabre,
} from './danse_macabre';

import {
  shouldCast as shouldCastDawn,
  execute as executeDawn,
  metadata as metadataDawn,
} from './dawn';

import {
  shouldCast as shouldCastDestructiveWave,
  execute as executeDestructiveWave,
  metadata as metadataDestructiveWave,
} from './destructive_wave';

import {
  shouldCast as shouldCastDominatePerson,
  execute as executeDominatePerson,
  metadata as metadataDominatePerson,
} from './dominate_person';

import {
  shouldCast as shouldCastEnervation,
  execute as executeEnervation,
  metadata as metadataEnervation,
} from './enervation';

import {
  shouldCast as shouldCastFlameStrike,
  execute as executeFlameStrike,
  metadata as metadataFlameStrike,
} from './flame_strike';

import {
  shouldCast as shouldCastGeas,
  execute as executeGeas,
  metadata as metadataGeas,
} from './geas';

import {
  shouldCast as shouldCastGreaterRestoration,
  execute as executeGreaterRestoration,
  metadata as metadataGreaterRestoration,
} from './greater_restoration';

import {
  shouldCast as shouldCastHoldMonster,
  execute as executeHoldMonster,
  metadata as metadataHoldMonster,
} from './hold_monster';

import {
  shouldCast as shouldCastHolyWeapon,
  execute as executeHolyWeapon,
  metadata as metadataHolyWeapon,
} from './holy_weapon';

import {
  shouldCast as shouldCastImmolation,
  execute as executeImmolation,
  metadata as metadataImmolation,
} from './immolation';

import {
  shouldCast as shouldCastInsectPlague,
  execute as executeInsectPlague,
  metadata as metadataInsectPlague,
} from './insect_plague';

import {
  shouldCast as shouldCastMaelstrom,
  execute as executeMaelstrom,
  metadata as metadataMaelstrom,
} from './maelstrom';

import {
  shouldCast as shouldCastMassCureWounds,
  execute as executeMassCureWounds,
  metadata as metadataMassCureWounds,
} from './mass_cure_wounds';

import {
  shouldCast as shouldCastMislead,
  execute as executeMislead,
  metadata as metadataMislead,
} from './mislead';

import {
  shouldCast as shouldCastModifyMemory,
  execute as executeModifyMemory,
  metadata as metadataModifyMemory,
} from './modify_memory';

import {
  shouldCast as shouldCastNegativeEnergyFlood,
  execute as executeNegativeEnergyFlood,
  metadata as metadataNegativeEnergyFlood,
} from './negative_energy_flood';

import {
  shouldCast as shouldCastPasswall,
  execute as executePasswall,
  metadata as metadataPasswall,
} from './passwall';

import {
  shouldCast as shouldCastRarysTelepathicBond,
  execute as executeRarysTelepathicBond,
  metadata as metadataRarysTelepathicBond,
} from './rarys_telepathic_bond';

import {
  shouldCast as shouldCastSeeming,
  execute as executeSeeming,
  metadata as metadataSeeming,
} from './seeming';

import {
  shouldCast as shouldCastSkillEmpowerment,
  execute as executeSkillEmpowerment,
  metadata as metadataSkillEmpowerment,
} from './skill_empowerment';

import {
  shouldCast as shouldCastSongalsElementalSuffusion,
  execute as executeSongalsElementalSuffusion,
  metadata as metadataSongalsElementalSuffusion,
} from './songals_elemental_suffusion';

import {
  shouldCast as shouldCastSteelWindStrike,
  execute as executeSteelWindStrike,
  metadata as metadataSteelWindStrike,
} from './steel_wind_strike';

import {
  shouldCast as shouldCastSwiftQuiver,
  execute as executeSwiftQuiver,
  metadata as metadataSwiftQuiver,
} from './swift_quiver';

import {
  shouldCast as shouldCastSynapticStatic,
  execute as executeSynapticStatic,
  metadata as metadataSynapticStatic,
} from './synaptic_static';

import {
  shouldCast as shouldCastTelekinesis,
  execute as executeTelekinesis,
  metadata as metadataTelekinesis,
} from './telekinesis';

import {
  shouldCast as shouldCastTemporalShunt,
  execute as executeTemporalShunt,
  metadata as metadataTemporalShunt,
} from './temporal_shunt';

import {
  shouldCast as shouldCastTransmuteRock,
  execute as executeTransmuteRock,
  metadata as metadataTransmuteRock,
} from './transmute_rock';

import {
  shouldCast as shouldCastTreeStride,
  execute as executeTreeStride,
  metadata as metadataTreeStride,
} from './tree_stride';

import {
  shouldCast as shouldCastWrathOfNature,
  execute as executeWrathOfNature,
  metadata as metadataWrathOfNature,
} from './wrath_of_nature';

import {
  shouldCast as shouldCastArcaneGate,
  execute as executeArcaneGate,
  metadata as metadataArcaneGate,
} from './arcane_gate';

import {
  shouldCast as shouldCastBladeBarrier,
  execute as executeBladeBarrier,
  metadata as metadataBladeBarrier,
} from './blade_barrier';

import {
  shouldCast as shouldCastBonesOfTheEarth,
  execute as executeBonesOfTheEarth,
  metadata as metadataBonesOfTheEarth,
} from './bones_of_the_earth';

import {
  shouldCast as shouldCastChainLightning,
  execute as executeChainLightning,
  metadata as metadataChainLightning,
} from './chain_lightning';

import {
  shouldCast as shouldCastCircleOfDeath,
  execute as executeCircleOfDeath,
  metadata as metadataCircleOfDeath,
} from './circle_of_death';

import {
  shouldCast as shouldCastCreateHomunculus,
  execute as executeCreateHomunculus,
  metadata as metadataCreateHomunculus,
} from './create_homunculus';

import {
  shouldCast as shouldCastDirge,
  execute as executeDirge,
  metadata as metadataDirge,
} from './dirge';

import {
  shouldCast as shouldCastDruidGrove,
  execute as executeDruidGrove,
  metadata as metadataDruidGrove,
} from './druid_grove';

import {
  shouldCast as shouldCastElminstersEffulgentSpheres,
  execute as executeElminstersEffulgentSpheres,
  metadata as metadataElminstersEffulgentSpheres,
} from './elminsters_effulgent_spheres';

import {
  shouldCast as shouldCastEyebite,
  execute as executeEyebite,
  metadata as metadataEyebite,
} from './eyebite';

import {
  shouldCast as shouldCastFizbansPlatinumShield,
  execute as executeFizbansPlatinumShield,
  metadata as metadataFizbansPlatinumShield,
} from './fizbans_platinum_shield';

import {
  shouldCast as shouldCastFleshToStone,
  execute as executeFleshToStone,
  metadata as metadataFleshToStone,
} from './flesh_to_stone';

import {
  shouldCast as shouldCastGlobeOfInvulnerability,
  execute as executeGlobeOfInvulnerability,
  metadata as metadataGlobeOfInvulnerability,
} from './globe_of_invulnerability';

import {
  shouldCast as shouldCastGravityFissure,
  execute as executeGravityFissure,
  metadata as metadataGravityFissure,
} from './gravity_fissure';

import {
  shouldCast as shouldCastHeal,
  execute as executeHeal,
  metadata as metadataHeal,
} from './heal';

import {
  shouldCast as shouldCastInvestitureOfFlame,
  execute as executeInvestitureOfFlame,
  metadata as metadataInvestitureOfFlame,
} from './investiture_of_flame';

import {
  shouldCast as shouldCastInvestitureOfIce,
  execute as executeInvestitureOfIce,
  metadata as metadataInvestitureOfIce,
} from './investiture_of_ice';

import {
  shouldCast as shouldCastInvestitureOfStone,
  execute as executeInvestitureOfStone,
  metadata as metadataInvestitureOfStone,
} from './investiture_of_stone';

import {
  shouldCast as shouldCastInvestitureOfWind,
  execute as executeInvestitureOfWind,
  metadata as metadataInvestitureOfWind,
} from './investiture_of_wind';

import {
  shouldCast as shouldCastMassSuggestion,
  execute as executeMassSuggestion,
  metadata as metadataMassSuggestion,
} from './mass_suggestion';

import {
  shouldCast as shouldCastMentalPrison,
  execute as executeMentalPrison,
  metadata as metadataMentalPrison,
} from './mental_prison';

import {
  shouldCast as shouldCastMoveEarth,
  execute as executeMoveEarth,
  metadata as metadataMoveEarth,
} from './move_earth';

import {
  shouldCast as shouldCastOtilukesFreezingSphere,
  execute as executeOtilukesFreezingSphere,
  metadata as metadataOtilukesFreezingSphere,
} from './otilukes_freezing_sphere';

import {
  shouldCast as shouldCastOttosIrresistibleDance,
  execute as executeOttosIrresistibleDance,
  metadata as metadataOttosIrresistibleDance,
} from './ottos_irresistible_dance';

import {
  shouldCast as shouldCastPrimordialWard,
  execute as executePrimordialWard,
  metadata as metadataPrimordialWard,
} from './primordial_ward';

import {
  shouldCast as shouldCastScatter,
  execute as executeScatter,
  metadata as metadataScatter,
} from './scatter';

import {
  shouldCast as shouldCastSoulCage,
  execute as executeSoulCage,
  metadata as metadataSoulCage,
} from './soul_cage';

import {
  shouldCast as shouldCastSunbeam,
  execute as executeSunbeam,
  metadata as metadataSunbeam,
} from './sunbeam';

import {
  shouldCast as shouldCastTashasOtherworldlyGuise,
  execute as executeTashasOtherworldlyGuise,
  metadata as metadataTashasOtherworldlyGuise,
} from './tashas_otherworldly_guise';

import {
  shouldCast as shouldCastTensersTransformation,
  execute as executeTensersTransformation,
  metadata as metadataTensersTransformation,
} from './tensers_transformation';

import {
  shouldCast as shouldCastTransportViaPlants,
  execute as executeTransportViaPlants,
  metadata as metadataTransportViaPlants,
} from './transport_via_plants';

import {
  shouldCast as shouldCastCrownOfStars,
  execute as executeCrownOfStars,
  metadata as metadataCrownOfStars,
} from './crown_of_stars';

import {
  shouldCast as shouldCastDelayedBlastFireball,
  execute as executeDelayedBlastFireball,
  metadata as metadataDelayedBlastFireball,
} from './delayed_blast_fireball';

import {
  shouldCast as shouldCastDivineWord,
  execute as executeDivineWord,
  metadata as metadataDivineWord,
} from './divine_word';

import {
  shouldCast as shouldCastDraconicTransformation,
  execute as executeDraconicTransformation,
  metadata as metadataDraconicTransformation,
} from './draconic_transformation';

import {
  shouldCast as shouldCastFireStorm,
  execute as executeFireStorm,
  metadata as metadataFireStorm,
} from './fire_storm';

import {
  shouldCast as shouldCastForcecage,
  execute as executeForcecage,
  metadata as metadataForcecage,
} from './forcecage';

import {
  shouldCast as shouldCastMirageArcane,
  execute as executeMirageArcane,
  metadata as metadataMirageArcane,
} from './mirage_arcane';

import {
  shouldCast as shouldCastMordenkainensMagnificentMansion,
  execute as executeMordenkainensMagnificentMansion,
  metadata as metadataMordenkainensMagnificentMansion,
} from './mordenkainens_magnificent_mansion';

import {
  shouldCast as shouldCastMordenkainensSword,
  execute as executeMordenkainensSword,
  metadata as metadataMordenkainensSword,
} from './mordenkainens_sword';

import {
  shouldCast as shouldCastPowerWordPain,
  execute as executePowerWordPain,
  metadata as metadataPowerWordPain,
} from './power_word_pain';

import {
  shouldCast as shouldCastPrismaticSpray,
  execute as executePrismaticSpray,
  metadata as metadataPrismaticSpray,
} from './prismatic_spray';

import {
  shouldCast as shouldCastProjectImage,
  execute as executeProjectImage,
  metadata as metadataProjectImage,
} from './project_image';

import {
  shouldCast as shouldCastRegenerate,
  execute as executeRegenerate,
  metadata as metadataRegenerate,
} from './regenerate';

import {
  shouldCast as shouldCastReverseGravity,
  execute as executeReverseGravity,
  metadata as metadataReverseGravity,
} from './reverse_gravity';

import {
  shouldCast as shouldCastSequester,
  execute as executeSequester,
  metadata as metadataSequester,
} from './sequester';

import {
  shouldCast as shouldCastSimbulsSynostodweomer,
  execute as executeSimbulsSynostodweomer,
  metadata as metadataSimbulsSynostodweomer,
} from './simbuls_synostodweomer';

import {
  shouldCast as shouldCastTetherEssence,
  execute as executeTetherEssence,
  metadata as metadataTetherEssence,
} from './tether_essence';

import {
  shouldCast as shouldCastWhirlwind,
  execute as executeWhirlwind,
  metadata as metadataWhirlwind,
} from './whirlwind';

import {
  shouldCast as shouldCastAbiDalzimsHorridWilting,
  execute as executeAbiDalzimsHorridWilting,
  metadata as metadataAbiDalzimsHorridWilting,
} from './abi_dalzims_horrid_wilting';

import {
  shouldCast as shouldCastAnimalShapes,
  execute as executeAnimalShapes,
  metadata as metadataAnimalShapes,
} from './animal_shapes';

import {
  shouldCast as shouldCastAntipathySympathy,
  execute as executeAntipathySympathy,
  metadata as metadataAntipathySympathy,
} from './antipathy_sympathy';

import {
  shouldCast as shouldCastControlWeather,
  execute as executeControlWeather,
  metadata as metadataControlWeather,
} from './control_weather';

import {
  shouldCast as shouldCastDarkStar,
  execute as executeDarkStar,
  metadata as metadataDarkStar,
} from './dark_star';

import {
  shouldCast as shouldCastDominateMonster,
  execute as executeDominateMonster,
  metadata as metadataDominateMonster,
} from './dominate_monster';

import {
  shouldCast as shouldCastEarthquake,
  execute as executeEarthquake,
  metadata as metadataEarthquake,
} from './earthquake';

import {
  shouldCast as shouldCastFeeblemind,
  execute as executeFeeblemind,
  metadata as metadataFeeblemind,
} from './feeblemind';

import {
  shouldCast as shouldCastGlibness,
  execute as executeGlibness,
  metadata as metadataGlibness,
} from './glibness';

import {
  shouldCast as shouldCastHolyAura,
  execute as executeHolyAura,
  metadata as metadataHolyAura,
} from './holy_aura';

import {
  shouldCast as shouldCastHolyStarOfMystra,
  execute as executeHolyStarOfMystra,
  metadata as metadataHolyStarOfMystra,
} from './holy_star_of_mystra';

import {
  shouldCast as shouldCastIllusoryDragon,
  execute as executeIllusoryDragon,
  metadata as metadataIllusoryDragon,
} from './illusory_dragon';

import {
  shouldCast as shouldCastIncendiaryCloud,
  execute as executeIncendiaryCloud,
  metadata as metadataIncendiaryCloud,
} from './incendiary_cloud';

import {
  shouldCast as shouldCastMaddeningDarkness,
  execute as executeMaddeningDarkness,
  metadata as metadataMaddeningDarkness,
} from './maddening_darkness';

import {
  shouldCast as shouldCastPowerWordStun,
  execute as executePowerWordStun,
  metadata as metadataPowerWordStun,
} from './power_word_stun';

import {
  shouldCast as shouldCastRealityBreak,
  execute as executeRealityBreak,
  metadata as metadataRealityBreak,
} from './reality_break';

import {
  shouldCast as shouldCastTsunami,
  execute as executeTsunami,
  metadata as metadataTsunami,
} from './tsunami';

import {
  shouldCast as shouldCastBladeOfDisaster,
  execute as executeBladeOfDisaster,
  metadata as metadataBladeOfDisaster,
} from './blade_of_disaster';

import {
  shouldCast as shouldCastForesight,
  execute as executeForesight,
  metadata as metadataForesight,
} from './foresight';

import {
  shouldCast as shouldCastInvulnerability,
  execute as executeInvulnerability,
  metadata as metadataInvulnerability,
} from './invulnerability';

import {
  shouldCast as shouldCastMassHeal,
  execute as executeMassHeal,
  metadata as metadataMassHeal,
} from './mass_heal';

import {
  shouldCast as shouldCastMassPolymorph,
  execute as executeMassPolymorph,
  metadata as metadataMassPolymorph,
} from './mass_polymorph';

import {
  shouldCast as shouldCastMeteorSwarm,
  execute as executeMeteorSwarm,
  metadata as metadataMeteorSwarm,
} from './meteor_swarm';

import {
  shouldCast as shouldCastPowerWordHeal,
  execute as executePowerWordHeal,
  metadata as metadataPowerWordHeal,
} from './power_word_heal';

import {
  shouldCast as shouldCastPsychicScream,
  execute as executePsychicScream,
  metadata as metadataPsychicScream,
} from './psychic_scream';

import {
  shouldCast as shouldCastRavenousVoid,
  execute as executeRavenousVoid,
  metadata as metadataRavenousVoid,
} from './ravenous_void';

import {
  shouldCast as shouldCastStormOfVengeance,
  execute as executeStormOfVengeance,
  metadata as metadataStormOfVengeance,
} from './storm_of_vengeance';

import {
  shouldCast as shouldCastTimeRavage,
  execute as executeTimeRavage,
  metadata as metadataTimeRavage,
} from './time_ravage';

import {
  shouldCast as shouldCastTimeStop,
  execute as executeTimeStop,
  metadata as metadataTimeStop,
} from './time_stop';

import {
  shouldCast as shouldCastWeird,
  execute as executeWeird,
  metadata as metadataWeird,
} from './weird';

// ---- Generic spell descriptor -------------------------------

import { Combatant, Battlefield } from '../types/core';
import { EngineState } from '../engine/combat';

export interface GenericSpellDescriptor {
  name: string;
  level: number;
  shouldCast: (caster: Combatant, bf: Battlefield) => boolean;
  execute: (caster: Combatant, state: EngineState) => void;
}

// ---- Registry keyed by canonical spell name -----------------

export const GENERIC_SPELLS: Record<string, GenericSpellDescriptor> = {
  'Alarm': {
    name: 'Alarm',
    level: metadataAlarm.level,
    shouldCast: shouldCastAlarm,
    execute: executeAlarm,
  },
  'Animal Friendship': {
    name: 'Animal Friendship',
    level: metadataAnimalFriendship.level,
    shouldCast: shouldCastAnimalFriendship,
    execute: executeAnimalFriendship,
  },
  'Armor of Agathys': {
    name: 'Armor of Agathys',
    level: metadataArmorOfAgathys.level,
    shouldCast: shouldCastArmorOfAgathys,
    execute: executeArmorOfAgathys,
  },
  'Bane': {
    name: 'Bane',
    level: metadataBane.level,
    shouldCast: shouldCastBane,
    execute: executeBane,
  },
  'Beast Bond': {
    name: 'Beast Bond',
    level: metadataBeastBond.level,
    shouldCast: shouldCastBeastBond,
    execute: executeBeastBond,
  },
  'Cause Fear': {
    name: 'Cause Fear',
    level: metadataCauseFear.level,
    shouldCast: shouldCastCauseFear,
    execute: executeCauseFear,
  },
  'Ceremony': {
    name: 'Ceremony',
    level: metadataCeremony.level,
    shouldCast: shouldCastCeremony,
    execute: executeCeremony,
  },
  'Charm Person': {
    name: 'Charm Person',
    level: metadataCharmPerson.level,
    shouldCast: shouldCastCharmPerson,
    execute: executeCharmPerson,
  },
  'Color Spray': {
    name: 'Color Spray',
    level: metadataColorSpray.level,
    shouldCast: shouldCastColorSpray,
    execute: executeColorSpray,
  },
  'Command': {
    name: 'Command',
    level: metadataCommand.level,
    shouldCast: shouldCastCommand,
    execute: executeCommand,
  },
  'Compelled Duel': {
    name: 'Compelled Duel',
    level: metadataCompelledDuel.level,
    shouldCast: shouldCastCompelledDuel,
    execute: executeCompelledDuel,
  },
  'Create or Destroy Water': {
    name: 'Create or Destroy Water',
    level: metadataCreateOrDestroyWater.level,
    shouldCast: shouldCastCreateOrDestroyWater,
    execute: executeCreateOrDestroyWater,
  },
  'Disguise Self': {
    name: 'Disguise Self',
    level: metadataDisguiseSelf.level,
    shouldCast: shouldCastDisguiseSelf,
    execute: executeDisguiseSelf,
  },
  'Distort Value': {
    name: 'Distort Value',
    level: metadataDistortValue.level,
    shouldCast: shouldCastDistortValue,
    execute: executeDistortValue,
  },
  'Divine Favor': {
    name: 'Divine Favor',
    level: metadataDivineFavor.level,
    shouldCast: shouldCastDivineFavor,
    execute: executeDivineFavor,
  },
  'Ensnaring Strike': {
    name: 'Ensnaring Strike',
    level: metadataEnsnaringStrike.level,
    shouldCast: shouldCastEnsnaringStrike,
    execute: executeEnsnaringStrike,
  },
  'Expeditious Retreat': {
    name: 'Expeditious Retreat',
    level: metadataExpeditiousRetreat.level,
    shouldCast: shouldCastExpeditiousRetreat,
    execute: executeExpeditiousRetreat,
  },
  'False Life': {
    name: 'False Life',
    level: metadataFalseLife.level,
    shouldCast: shouldCastFalseLife,
    execute: executeFalseLife,
  },
  'Gift of Alacrity': {
    name: 'Gift of Alacrity',
    level: metadataGiftOfAlacrity.level,
    shouldCast: shouldCastGiftOfAlacrity,
    execute: executeGiftOfAlacrity,
  },
  'Goodberry': {
    name: 'Goodberry',
    level: metadataGoodberry.level,
    shouldCast: shouldCastGoodberry,
    execute: executeGoodberry,
  },
  'Grease': {
    name: 'Grease',
    level: metadataGrease.level,
    shouldCast: shouldCastGrease,
    execute: executeGrease,
  },
  'Hail of Thorns': {
    name: 'Hail of Thorns',
    level: metadataHailOfThorns.level,
    shouldCast: shouldCastHailOfThorns,
    execute: executeHailOfThorns,
  },
  'Heroism': {
    name: 'Heroism',
    level: metadataHeroism.level,
    shouldCast: shouldCastHeroism,
    execute: executeHeroism,
  },
  "Hunter's Mark": {
    name: "Hunter's Mark",
    level: metadataHuntersMark.level,
    shouldCast: shouldCastHuntersMark,
    execute: executeHuntersMark,
  },
  "Jim's Magic Missile": {
    name: "Jim's Magic Missile",
    level: metadataJimsMagicMissile.level,
    shouldCast: shouldCastJimsMagicMissile,
    execute: executeJimsMagicMissile,
  },
  'Jump': {
    name: 'Jump',
    level: metadataJump.level,
    shouldCast: shouldCastJump,
    execute: executeJump,
  },
  'Purify Food and Drink': {
    name: 'Purify Food and Drink',
    level: metadataPurifyFoodAndDrink.level,
    shouldCast: shouldCastPurifyFoodAndDrink,
    execute: executePurifyFoodAndDrink,
  },
  'Sanctuary': {
    name: 'Sanctuary',
    level: metadataSanctuary.level,
    shouldCast: shouldCastSanctuary,
    execute: executeSanctuary,
  },
  'Searing Smite': {
    name: 'Searing Smite',
    level: metadataSearingSmite.level,
    shouldCast: shouldCastSearingSmite,
    execute: executeSearingSmite,
  },
  'Silent Image': {
    name: 'Silent Image',
    level: metadataSilentImage.level,
    shouldCast: shouldCastSilentImage,
    execute: executeSilentImage,
  },
  'Snare': {
    name: 'Snare',
    level: metadataSnare.level,
    shouldCast: shouldCastSnare,
    execute: executeSnare,
  },
  'Speak with Animals': {
    name: 'Speak with Animals',
    level: metadataSpeakWithAnimals.level,
    shouldCast: shouldCastSpeakWithAnimals,
    execute: executeSpeakWithAnimals,
  },
  "Tasha's Caustic Brew": {
    name: "Tasha's Caustic Brew",
    level: metadataTashasCausticBrew.level,
    shouldCast: shouldCastTashasCausticBrew,
    execute: executeTashasCausticBrew,
  },
  "Tasha's Hideous Laughter": {
    name: "Tasha's Hideous Laughter",
    level: metadataTashasHideousLaughter.level,
    shouldCast: shouldCastTashasHideousLaughter,
    execute: executeTashasHideousLaughter,
  },
  "Tenser's Floating Disk": {
    name: "Tenser's Floating Disk",
    level: metadataTensersFloatingDisk.level,
    shouldCast: shouldCastTensersFloatingDisk,
    execute: executeTensersFloatingDisk,
  },
  'Thunderous Smite': {
    name: 'Thunderous Smite',
    level: metadataThunderousSmite.level,
    shouldCast: shouldCastThunderousSmite,
    execute: executeThunderousSmite,
  },
  'Unseen Servant': {
    name: 'Unseen Servant',
    level: metadataUnseenServant.level,
    shouldCast: shouldCastUnseenServant,
    execute: executeUnseenServant,
  },
  'Wrathful Smite': {
    name: 'Wrathful Smite',
    level: metadataWrathfulSmite.level,
    shouldCast: shouldCastWrathfulSmite,
    execute: executeWrathfulSmite,
  },
  'Zephyr Strike': {
    name: 'Zephyr Strike',
    level: metadataZephyrStrike.level,
    shouldCast: shouldCastZephyrStrike,
    execute: executeZephyrStrike,
  },
  "Aganazzar's Scorcher": {
    name: "Aganazzar's Scorcher",
    level: metadataAganazzarsScorcher.level,
    shouldCast: shouldCastAganazzarsScorcher,
    execute: executeAganazzarsScorcher,
  },
  'Air Bubble': {
    name: 'Air Bubble',
    level: metadataAirBubble.level,
    shouldCast: shouldCastAirBubble,
    execute: executeAirBubble,
  },
  'Animal Messenger': {
    name: 'Animal Messenger',
    level: metadataAnimalMessenger.level,
    shouldCast: shouldCastAnimalMessenger,
    execute: executeAnimalMessenger,
  },
  'Beast Sense': {
    name: 'Beast Sense',
    level: metadataBeastSense.level,
    shouldCast: shouldCastBeastSense,
    execute: executeBeastSense,
  },
  'Borrowed Knowledge': {
    name: 'Borrowed Knowledge',
    level: metadataBorrowedKnowledge.level,
    shouldCast: shouldCastBorrowedKnowledge,
    execute: executeBorrowedKnowledge,
  },
  'Continual Flame': {
    name: 'Continual Flame',
    level: metadataContinualFlame.level,
    shouldCast: shouldCastContinualFlame,
    execute: executeContinualFlame,
  },
  'Death Armor': {
    name: 'Death Armor',
    level: metadataDeathArmor.level,
    shouldCast: shouldCastDeathArmor,
    execute: executeDeathArmor,
  },
  "Deryan's Helpful Homunculi": {
    name: "Deryan's Helpful Homunculi",
    level: metadataDeryansHelpfulHomunculi.level,
    shouldCast: shouldCastDeryansHelpfulHomunculi,
    execute: executeDeryansHelpfulHomunculi,
  },
  "Dragon's Breath": {
    name: "Dragon's Breath",
    level: metadataDragonsBreath.level,
    shouldCast: shouldCastDragonsBreath,
    execute: executeDragonsBreath,
  },
  'Dust Devil': {
    name: 'Dust Devil',
    level: metadataDustDevil.level,
    shouldCast: shouldCastDustDevil,
    execute: executeDustDevil,
  },
  'Earthbind': {
    name: 'Earthbind',
    level: metadataEarthbind.level,
    shouldCast: shouldCastEarthbind,
    execute: executeEarthbind,
  },
  "Elminster's Elusion": {
    name: "Elminster's Elusion",
    level: metadataElminstersElusion.level,
    shouldCast: shouldCastElminstersElusion,
    execute: executeElminstersElusion,
  },
  'Find Traps': {
    name: 'Find Traps',
    level: metadataFindTraps.level,
    shouldCast: shouldCastFindTraps,
    execute: executeFindTraps,
  },
  'Flock of Familiars': {
    name: 'Flock of Familiars',
    level: metadataFlockOfFamiliars.level,
    shouldCast: shouldCastFlockOfFamiliars,
    execute: executeFlockOfFamiliars,
  },
  "Fortune's Favor": {
    name: "Fortune's Favor",
    level: metadataFortunesFavor.level,
    shouldCast: shouldCastFortunesFavor,
    execute: executeFortunesFavor,
  },
  'Gift of Gab': {
    name: 'Gift of Gab',
    level: metadataGiftOfGab.level,
    shouldCast: shouldCastGiftOfGab,
    execute: executeGiftOfGab,
  },
  'Healing Spirit': {
    name: 'Healing Spirit',
    level: metadataHealingSpirit.level,
    shouldCast: shouldCastHealingSpirit,
    execute: executeHealingSpirit,
  },
  'Homunculus Servant': {
    name: 'Homunculus Servant',
    level: metadataHomunculusServant.level,
    shouldCast: shouldCastHomunculusServant,
    execute: executeHomunculusServant,
  },
  'Immovable Object': {
    name: 'Immovable Object',
    level: metadataImmovableObject.level,
    shouldCast: shouldCastImmovableObject,
    execute: executeImmovableObject,
  },
  "Jim's Glowing Coin": {
    name: "Jim's Glowing Coin",
    level: metadataJimsGlowingCoin.level,
    shouldCast: shouldCastJimsGlowingCoin,
    execute: executeJimsGlowingCoin,
  },
  'Kinetic Jaunt': {
    name: 'Kinetic Jaunt',
    level: metadataKineticJaunt.level,
    shouldCast: shouldCastKineticJaunt,
    execute: executeKineticJaunt,
  },
  'Magic Mouth': {
    name: 'Magic Mouth',
    level: metadataMagicMouth.level,
    shouldCast: shouldCastMagicMouth,
    execute: executeMagicMouth,
  },
  "Maximilian's Earthen Grasp": {
    name: "Maximilian's Earthen Grasp",
    level: metadataMaximiliansEarthenGrasp.level,
    shouldCast: shouldCastMaximiliansEarthenGrasp,
    execute: executeMaximiliansEarthenGrasp,
  },
  "Nathair's Mischief": {
    name: "Nathair's Mischief",
    level: metadataNathairsMischief.level,
    shouldCast: shouldCastNathairsMischief,
    execute: executeNathairsMischief,
  },
  "Nystul's Magic Aura": {
    name: "Nystul's Magic Aura",
    level: metadataNystulsMagicAura.level,
    shouldCast: shouldCastNystulsMagicAura,
    execute: executeNystulsMagicAura,
  },
  'Pyrotechnics': {
    name: 'Pyrotechnics',
    level: metadataPyrotechnics.level,
    shouldCast: shouldCastPyrotechnics,
    execute: executePyrotechnics,
  },
  "Rime's Binding Ice": {
    name: "Rime's Binding Ice",
    level: metadataRimesBindingIce.level,
    shouldCast: shouldCastRimesBindingIce,
    execute: executeRimesBindingIce,
  },
  'Shadow Blade': {
    name: 'Shadow Blade',
    level: metadataShadowBlade.level,
    shouldCast: shouldCastShadowBlade,
    execute: executeShadowBlade,
  },
  'Skywrite': {
    name: 'Skywrite',
    level: metadataSkywrite.level,
    shouldCast: shouldCastSkywrite,
    execute: executeSkywrite,
  },
  "Snilloc's Snowball Swarm": {
    name: "Snilloc's Snowball Swarm",
    level: metadataSnillocsSnowballSwarm.level,
    shouldCast: shouldCastSnillocsSnowballSwarm,
    execute: executeSnillocsSnowballSwarm,
  },
  "Tasha's Mind Whip": {
    name: "Tasha's Mind Whip",
    level: metadataTashasMindWhip.level,
    shouldCast: shouldCastTashasMindWhip,
    execute: executeTashasMindWhip,
  },
  'Vortex Warp': {
    name: 'Vortex Warp',
    level: metadataVortexWarp.level,
    shouldCast: shouldCastVortexWarp,
    execute: executeVortexWarp,
  },
  'Warding Wind': {
    name: 'Warding Wind',
    level: metadataWardingWind.level,
    shouldCast: shouldCastWardingWind,
    execute: executeWardingWind,
  },
  'Warp Sense': {
    name: 'Warp Sense',
    level: metadataWarpSense.level,
    shouldCast: shouldCastWarpSense,
    execute: executeWarpSense,
  },
  'Wither and Bloom': {
    name: 'Wither and Bloom',
    level: metadataWitherAndBloom.level,
    shouldCast: shouldCastWitherAndBloom,
    execute: executeWitherAndBloom,
  },
  'Wristpocket': {
    name: 'Wristpocket',
    level: metadataWristpocket.level,
    shouldCast: shouldCastWristpocket,
    execute: executeWristpocket,
  },
  'Antagonize': {
    name: 'Antagonize',
    level: metadataAntagonize.level,
    shouldCast: shouldCastAntagonize,
    execute: executeAntagonize,
  },
  "Ashardalon's Stride": {
    name: "Ashardalon's Stride",
    level: metadataAshardalonsStride.level,
    shouldCast: shouldCastAshardalonsStride,
    execute: executeAshardalonsStride,
  },
  'Aura of Vitality': {
    name: 'Aura of Vitality',
    level: metadataAuraOfVitality.level,
    shouldCast: shouldCastAuraOfVitality,
    execute: executeAuraOfVitality,
  },
  'Beacon of Hope': {
    name: 'Beacon of Hope',
    level: metadataBeaconOfHope.level,
    shouldCast: shouldCastBeaconOfHope,
    execute: executeBeaconOfHope,
  },
  'Bestow Curse': {
    name: 'Bestow Curse',
    level: metadataBestowCurse.level,
    shouldCast: shouldCastBestowCurse,
    execute: executeBestowCurse,
  },
  'Blinding Smite': {
    name: 'Blinding Smite',
    level: metadataBlindingSmite.level,
    shouldCast: shouldCastBlindingSmite,
    execute: executeBlindingSmite,
  },
  'Blink': {
    name: 'Blink',
    level: metadataBlink.level,
    shouldCast: shouldCastBlink,
    execute: executeBlink,
  },
  'Cacophonic Shield': {
    name: 'Cacophonic Shield',
    level: metadataCacophonicShield.level,
    shouldCast: shouldCastCacophonicShield,
    execute: executeCacophonicShield,
  },
  'Call Lightning': {
    name: 'Call Lightning',
    level: metadataCallLightning.level,
    shouldCast: shouldCastCallLightning,
    execute: executeCallLightning,
  },
  'Catnap': {
    name: 'Catnap',
    level: metadataCatnap.level,
    shouldCast: shouldCastCatnap,
    execute: executeCatnap,
  },
  'Create Food and Water': {
    name: 'Create Food and Water',
    level: metadataCreateFoodAndWater.level,
    shouldCast: shouldCastCreateFoodAndWater,
    execute: executeCreateFoodAndWater,
  },
  "Crusader's Mantle": {
    name: "Crusader's Mantle",
    level: metadataCrusadersMantle.level,
    shouldCast: shouldCastCrusadersMantle,
    execute: executeCrusadersMantle,
  },
  'Daylight': {
    name: 'Daylight',
    level: metadataDaylight.level,
    shouldCast: shouldCastDaylight,
    execute: executeDaylight,
  },
  'Elemental Weapon': {
    name: 'Elemental Weapon',
    level: metadataElementalWeapon.level,
    shouldCast: shouldCastElementalWeapon,
    execute: executeElementalWeapon,
  },
  'Enemies Abound': {
    name: 'Enemies Abound',
    level: metadataEnemiesAbound.level,
    shouldCast: shouldCastEnemiesAbound,
    execute: executeEnemiesAbound,
  },
  'Erupting Earth': {
    name: 'Erupting Earth',
    level: metadataEruptingEarth.level,
    shouldCast: shouldCastEruptingEarth,
    execute: executeEruptingEarth,
  },
  'Fast Friends': {
    name: 'Fast Friends',
    level: metadataFastFriends.level,
    shouldCast: shouldCastFastFriends,
    execute: executeFastFriends,
  },
  'Fear': {
    name: 'Fear',
    level: metadataFear.level,
    shouldCast: shouldCastFear,
    execute: executeFear,
  },
  'Feign Death': {
    name: 'Feign Death',
    level: metadataFeignDeath.level,
    shouldCast: shouldCastFeignDeath,
    execute: executeFeignDeath,
  },
  'Flame Arrows': {
    name: 'Flame Arrows',
    level: metadataFlameArrows.level,
    shouldCast: shouldCastFlameArrows,
    execute: executeFlameArrows,
  },
  'Fly': {
    name: 'Fly',
    level: metadataFly.level,
    shouldCast: shouldCastFly,
    execute: executeFly,
  },
  "Galder's Tower": {
    name: "Galder's Tower",
    level: metadataGaldersTower.level,
    shouldCast: shouldCastGaldersTower,
    execute: executeGaldersTower,
  },
  'Gaseous Form': {
    name: 'Gaseous Form',
    level: metadataGaseousForm.level,
    shouldCast: shouldCastGaseousForm,
    execute: executeGaseousForm,
  },
  'Haste': {
    name: 'Haste',
    level: metadataHaste.level,
    shouldCast: shouldCastHaste,
    execute: executeHaste,
  },
  'Hunger of Hadar': {
    name: 'Hunger of Hadar',
    level: metadataHungerOfHadar.level,
    shouldCast: shouldCastHungerOfHadar,
    execute: executeHungerOfHadar,
  },
  'Hypnotic Pattern': {
    name: 'Hypnotic Pattern',
    level: metadataHypnoticPattern.level,
    shouldCast: shouldCastHypnoticPattern,
    execute: executeHypnoticPattern,
  },
  'Incite Greed': {
    name: 'Incite Greed',
    level: metadataInciteGreed.level,
    shouldCast: shouldCastInciteGreed,
    execute: executeInciteGreed,
  },
  'Intellect Fortress': {
    name: 'Intellect Fortress',
    level: metadataIntellectFortress.level,
    shouldCast: shouldCastIntellectFortress,
    execute: executeIntellectFortress,
  },
  "Laeral's Silver Lance": {
    name: "Laeral's Silver Lance",
    level: metadataLaeralsSilverLance.level,
    shouldCast: shouldCastLaeralsSilverLance,
    execute: executeLaeralsSilverLance,
  },
  "Leomund's Tiny Hut": {
    name: "Leomund's Tiny Hut",
    level: metadataLeomundsTinyHut.level,
    shouldCast: shouldCastLeomundsTinyHut,
    execute: executeLeomundsTinyHut,
  },
  'Life Transference': {
    name: 'Life Transference',
    level: metadataLifeTransference.level,
    shouldCast: shouldCastLifeTransference,
    execute: executeLifeTransference,
  },
  'Lightning Arrow': {
    name: 'Lightning Arrow',
    level: metadataLightningArrow.level,
    shouldCast: shouldCastLightningArrow,
    execute: executeLightningArrow,
  },
  'Linked Glyphs': {
    name: 'Linked Glyphs',
    level: metadataLinkedGlyphs.level,
    shouldCast: shouldCastLinkedGlyphs,
    execute: executeLinkedGlyphs,
  },
  'Major Image': {
    name: 'Major Image',
    level: metadataMajorImage.level,
    shouldCast: shouldCastMajorImage,
    execute: executeMajorImage,
  },
  'Mass Healing Word': {
    name: 'Mass Healing Word',
    level: metadataMassHealingWord.level,
    shouldCast: shouldCastMassHealingWord,
    execute: executeMassHealingWord,
  },
  'Meld into Stone': {
    name: 'Meld into Stone',
    level: metadataMeldIntoStone.level,
    shouldCast: shouldCastMeldIntoStone,
    execute: executeMeldIntoStone,
  },
  "Melf's Minute Meteors": {
    name: "Melf's Minute Meteors",
    level: metadataMelfsMinuteMeteors.level,
    shouldCast: shouldCastMelfsMinuteMeteors,
    execute: executeMelfsMinuteMeteors,
  },
  'Motivational Speech': {
    name: 'Motivational Speech',
    level: metadataMotivationalSpeech.level,
    shouldCast: shouldCastMotivationalSpeech,
    execute: executeMotivationalSpeech,
  },
  'Nondetection': {
    name: 'Nondetection',
    level: metadataNondetection.level,
    shouldCast: shouldCastNondetection,
    execute: executeNondetection,
  },
  'Phantom Steed': {
    name: 'Phantom Steed',
    level: metadataPhantomSteed.level,
    shouldCast: shouldCastPhantomSteed,
    execute: executePhantomSteed,
  },
  'Plant Growth': {
    name: 'Plant Growth',
    level: metadataPlantGrowth.level,
    shouldCast: shouldCastPlantGrowth,
    execute: executePlantGrowth,
  },
  'Pulse Wave': {
    name: 'Pulse Wave',
    level: metadataPulseWave.level,
    shouldCast: shouldCastPulseWave,
    execute: executePulseWave,
  },
  'Remove Curse': {
    name: 'Remove Curse',
    level: metadataRemoveCurse.level,
    shouldCast: shouldCastRemoveCurse,
    execute: executeRemoveCurse,
  },
  'Sleet Storm': {
    name: 'Sleet Storm',
    level: metadataSleetStorm.level,
    shouldCast: shouldCastSleetStorm,
    execute: executeSleetStorm,
  },
  'Slow': {
    name: 'Slow',
    level: metadataSlow.level,
    shouldCast: shouldCastSlow,
    execute: executeSlow,
  },
  'Speak with Dead': {
    name: 'Speak with Dead',
    level: metadataSpeakWithDead.level,
    shouldCast: shouldCastSpeakWithDead,
    execute: executeSpeakWithDead,
  },
  'Speak with Plants': {
    name: 'Speak with Plants',
    level: metadataSpeakWithPlants.level,
    shouldCast: shouldCastSpeakWithPlants,
    execute: executeSpeakWithPlants,
  },
  'Spirit Guardians': {
    name: 'Spirit Guardians',
    level: metadataSpiritGuardians.level,
    shouldCast: shouldCastSpiritGuardians,
    execute: executeSpiritGuardians,
  },
  'Spirit Shroud': {
    name: 'Spirit Shroud',
    level: metadataSpiritShroud.level,
    shouldCast: shouldCastSpiritShroud,
    execute: executeSpiritShroud,
  },
  'Stinking Cloud': {
    name: 'Stinking Cloud',
    level: metadataStinkingCloud.level,
    shouldCast: shouldCastStinkingCloud,
    execute: executeStinkingCloud,
  },
  "Syluné's Viper": {
    name: "Syluné's Viper",
    level: metadataSylunésViper.level,
    shouldCast: shouldCastSylunésViper,
    execute: executeSylunésViper,
  },
  'Tidal Wave': {
    name: 'Tidal Wave',
    level: metadataTidalWave.level,
    shouldCast: shouldCastTidalWave,
    execute: executeTidalWave,
  },
  'Tiny Servant': {
    name: 'Tiny Servant',
    level: metadataTinyServant.level,
    shouldCast: shouldCastTinyServant,
    execute: executeTinyServant,
  },
  'Vampiric Touch': {
    name: 'Vampiric Touch',
    level: metadataVampiricTouch.level,
    shouldCast: shouldCastVampiricTouch,
    execute: executeVampiricTouch,
  },
  'Aura of Life': {
    name: 'Aura of Life',
    level: metadataAuraOfLife.level,
    shouldCast: shouldCastAuraOfLife,
    execute: executeAuraOfLife,
  },
  'Aura of Purity': {
    name: 'Aura of Purity',
    level: metadataAuraOfPurity.level,
    shouldCast: shouldCastAuraOfPurity,
    execute: executeAuraOfPurity,
  },
  'Backlash': {
    name: 'Backlash',
    level: metadataBacklash.level,
    shouldCast: shouldCastBacklash,
    execute: executeBacklash,
  },
  'Charm Monster': {
    name: 'Charm Monster',
    level: metadataCharmMonster.level,
    shouldCast: shouldCastCharmMonster,
    execute: executeCharmMonster,
  },
  'Compulsion': {
    name: 'Compulsion',
    level: metadataCompulsion.level,
    shouldCast: shouldCastCompulsion,
    execute: executeCompulsion,
  },
  'Confusion': {
    name: 'Confusion',
    level: metadataConfusion.level,
    shouldCast: shouldCastConfusion,
    execute: executeConfusion,
  },
  'Control Water': {
    name: 'Control Water',
    level: metadataControlWater.level,
    shouldCast: shouldCastControlWater,
    execute: executeControlWater,
  },
  'Death Ward': {
    name: 'Death Ward',
    level: metadataDeathWard.level,
    shouldCast: shouldCastDeathWard,
    execute: executeDeathWard,
  },
  'Dominate Beast': {
    name: 'Dominate Beast',
    level: metadataDominateBeast.level,
    shouldCast: shouldCastDominateBeast,
    execute: executeDominateBeast,
  },
  'Doomtide': {
    name: 'Doomtide',
    level: metadataDoomtide.level,
    shouldCast: shouldCastDoomtide,
    execute: executeDoomtide,
  },
  'Elemental Bane': {
    name: 'Elemental Bane',
    level: metadataElementalBane.level,
    shouldCast: shouldCastElementalBane,
    execute: executeElementalBane,
  },
  "Evard's Black Tentacles": {
    name: "Evard's Black Tentacles",
    level: metadataEvardsBlackTentacles.level,
    shouldCast: shouldCastEvardsBlackTentacles,
    execute: executeEvardsBlackTentacles,
  },
  'Fabricate': {
    name: 'Fabricate',
    level: metadataFabricate.level,
    shouldCast: shouldCastFabricate,
    execute: executeFabricate,
  },
  'Fire Shield': {
    name: 'Fire Shield',
    level: metadataFireShield.level,
    shouldCast: shouldCastFireShield,
    execute: executeFireShield,
  },
  'Freedom of Movement': {
    name: 'Freedom of Movement',
    level: metadataFreedomOfMovement.level,
    shouldCast: shouldCastFreedomOfMovement,
    execute: executeFreedomOfMovement,
  },
  "Galder's Speedy Courier": {
    name: "Galder's Speedy Courier",
    level: metadataGaldersSpeedyCourier.level,
    shouldCast: shouldCastGaldersSpeedyCourier,
    execute: executeGaldersSpeedyCourier,
  },
  'Gate Seal': {
    name: 'Gate Seal',
    level: metadataGateSeal.level,
    shouldCast: shouldCastGateSeal,
    execute: executeGateSeal,
  },
  'Giant Insect': {
    name: 'Giant Insect',
    level: metadataGiantInsect.level,
    shouldCast: shouldCastGiantInsect,
    execute: executeGiantInsect,
  },
  'Grasping Vine': {
    name: 'Grasping Vine',
    level: metadataGraspingVine.level,
    shouldCast: shouldCastGraspingVine,
    execute: executeGraspingVine,
  },
  'Gravity Sinkhole': {
    name: 'Gravity Sinkhole',
    level: metadataGravitySinkhole.level,
    shouldCast: shouldCastGravitySinkhole,
    execute: executeGravitySinkhole,
  },
  'Guardian of Faith': {
    name: 'Guardian of Faith',
    level: metadataGuardianOfFaith.level,
    shouldCast: shouldCastGuardianOfFaith,
    execute: executeGuardianOfFaith,
  },
  'Guardian of Nature': {
    name: 'Guardian of Nature',
    level: metadataGuardianOfNature.level,
    shouldCast: shouldCastGuardianOfNature,
    execute: executeGuardianOfNature,
  },
  'Hallucinatory Terrain': {
    name: 'Hallucinatory Terrain',
    level: metadataHallucinatoryTerrain.level,
    shouldCast: shouldCastHallucinatoryTerrain,
    execute: executeHallucinatoryTerrain,
  },
  'Ice Storm': {
    name: 'Ice Storm',
    level: metadataIceStorm.level,
    shouldCast: shouldCastIceStorm,
    execute: executeIceStorm,
  },
  "Mordenkainen's Faithful Hound": {
    name: "Mordenkainen's Faithful Hound",
    level: metadataMordenkainensFaithfulHound.level,
    shouldCast: shouldCastMordenkainensFaithfulHound,
    execute: executeMordenkainensFaithfulHound,
  },
  "Mordenkainen's Private Sanctum": {
    name: "Mordenkainen's Private Sanctum",
    level: metadataMordenkainensPrivateSanctum.level,
    shouldCast: shouldCastMordenkainensPrivateSanctum,
    execute: executeMordenkainensPrivateSanctum,
  },
  "Otiluke's Resilient Sphere": {
    name: "Otiluke's Resilient Sphere",
    level: metadataOtilukesResilientSphere.level,
    shouldCast: shouldCastOtilukesResilientSphere,
    execute: executeOtilukesResilientSphere,
  },
  'Phantasmal Killer': {
    name: 'Phantasmal Killer',
    level: metadataPhantasmalKiller.level,
    shouldCast: shouldCastPhantasmalKiller,
    execute: executePhantasmalKiller,
  },
  'Polymorph': {
    name: 'Polymorph',
    level: metadataPolymorph.level,
    shouldCast: shouldCastPolymorph,
    execute: executePolymorph,
  },
  "Raulothim's Psychic Lance": {
    name: "Raulothim's Psychic Lance",
    level: metadataRaulothimsPsychicLance.level,
    shouldCast: shouldCastRaulothimsPsychicLance,
    execute: executeRaulothimsPsychicLance,
  },
  'Shadow of Moil': {
    name: 'Shadow of Moil',
    level: metadataShadowOfMoil.level,
    shouldCast: shouldCastShadowOfMoil,
    execute: executeShadowOfMoil,
  },
  'Sickening Radiance': {
    name: 'Sickening Radiance',
    level: metadataSickeningRadiance.level,
    shouldCast: shouldCastSickeningRadiance,
    execute: executeSickeningRadiance,
  },
  'Spellfire Storm': {
    name: 'Spellfire Storm',
    level: metadataSpellfireStorm.level,
    shouldCast: shouldCastSpellfireStorm,
    execute: executeSpellfireStorm,
  },
  'Spirit of Death': {
    name: 'Spirit of Death',
    level: metadataSpiritOfDeath.level,
    shouldCast: shouldCastSpiritOfDeath,
    execute: executeSpiritOfDeath,
  },
  'Staggering Smite': {
    name: 'Staggering Smite',
    level: metadataStaggeringSmite.level,
    shouldCast: shouldCastStaggeringSmite,
    execute: executeStaggeringSmite,
  },
  'Stone Shape': {
    name: 'Stone Shape',
    level: metadataStoneShape.level,
    shouldCast: shouldCastStoneShape,
    execute: executeStoneShape,
  },
  'Stoneskin': {
    name: 'Stoneskin',
    level: metadataStoneskin.level,
    shouldCast: shouldCastStoneskin,
    execute: executeStoneskin,
  },
  'Storm Sphere': {
    name: 'Storm Sphere',
    level: metadataStormSphere.level,
    shouldCast: shouldCastStormSphere,
    execute: executeStormSphere,
  },
  'Vitriolic Sphere': {
    name: 'Vitriolic Sphere',
    level: metadataVitriolicSphere.level,
    shouldCast: shouldCastVitriolicSphere,
    execute: executeVitriolicSphere,
  },
  'Watery Sphere': {
    name: 'Watery Sphere',
    level: metadataWaterySphere.level,
    shouldCast: shouldCastWaterySphere,
    execute: executeWaterySphere,
  },
  "Alustriel's Mooncloak": {
    name: "Alustriel's Mooncloak",
    level: metadataAlustrielsMooncloak.level,
    shouldCast: shouldCastAlustrielsMooncloak,
    execute: executeAlustrielsMooncloak,
  },
  'Animate Objects': {
    name: 'Animate Objects',
    level: metadataAnimateObjects.level,
    shouldCast: shouldCastAnimateObjects,
    execute: executeAnimateObjects,
  },
  'Antilife Shell': {
    name: 'Antilife Shell',
    level: metadataAntilifeShell.level,
    shouldCast: shouldCastAntilifeShell,
    execute: executeAntilifeShell,
  },
  'Banishing Smite': {
    name: 'Banishing Smite',
    level: metadataBanishingSmite.level,
    shouldCast: shouldCastBanishingSmite,
    execute: executeBanishingSmite,
  },
  "Bigby's Hand": {
    name: "Bigby's Hand",
    level: metadataBigbysHand.level,
    shouldCast: shouldCastBigbysHand,
    execute: executeBigbysHand,
  },
  'Circle of Power': {
    name: 'Circle of Power',
    level: metadataCircleOfPower.level,
    shouldCast: shouldCastCircleOfPower,
    execute: executeCircleOfPower,
  },
  'Commune with Nature': {
    name: 'Commune with Nature',
    level: metadataCommuneWithNature.level,
    shouldCast: shouldCastCommuneWithNature,
    execute: executeCommuneWithNature,
  },
  'Contagion': {
    name: 'Contagion',
    level: metadataContagion.level,
    shouldCast: shouldCastContagion,
    execute: executeContagion,
  },
  'Control Winds': {
    name: 'Control Winds',
    level: metadataControlWinds.level,
    shouldCast: shouldCastControlWinds,
    execute: executeControlWinds,
  },
  'Create Spelljamming Helm': {
    name: 'Create Spelljamming Helm',
    level: metadataCreateSpelljammingHelm.level,
    shouldCast: shouldCastCreateSpelljammingHelm,
    execute: executeCreateSpelljammingHelm,
  },
  'Creation': {
    name: 'Creation',
    level: metadataCreation.level,
    shouldCast: shouldCastCreation,
    execute: executeCreation,
  },
  'Danse Macabre': {
    name: 'Danse Macabre',
    level: metadataDanseMacabre.level,
    shouldCast: shouldCastDanseMacabre,
    execute: executeDanseMacabre,
  },
  'Dawn': {
    name: 'Dawn',
    level: metadataDawn.level,
    shouldCast: shouldCastDawn,
    execute: executeDawn,
  },
  'Destructive Wave': {
    name: 'Destructive Wave',
    level: metadataDestructiveWave.level,
    shouldCast: shouldCastDestructiveWave,
    execute: executeDestructiveWave,
  },
  'Dominate Person': {
    name: 'Dominate Person',
    level: metadataDominatePerson.level,
    shouldCast: shouldCastDominatePerson,
    execute: executeDominatePerson,
  },
  'Enervation': {
    name: 'Enervation',
    level: metadataEnervation.level,
    shouldCast: shouldCastEnervation,
    execute: executeEnervation,
  },
  'Flame Strike': {
    name: 'Flame Strike',
    level: metadataFlameStrike.level,
    shouldCast: shouldCastFlameStrike,
    execute: executeFlameStrike,
  },
  'Geas': {
    name: 'Geas',
    level: metadataGeas.level,
    shouldCast: shouldCastGeas,
    execute: executeGeas,
  },
  'Greater Restoration': {
    name: 'Greater Restoration',
    level: metadataGreaterRestoration.level,
    shouldCast: shouldCastGreaterRestoration,
    execute: executeGreaterRestoration,
  },
  'Hold Monster': {
    name: 'Hold Monster',
    level: metadataHoldMonster.level,
    shouldCast: shouldCastHoldMonster,
    execute: executeHoldMonster,
  },
  'Holy Weapon': {
    name: 'Holy Weapon',
    level: metadataHolyWeapon.level,
    shouldCast: shouldCastHolyWeapon,
    execute: executeHolyWeapon,
  },
  'Immolation': {
    name: 'Immolation',
    level: metadataImmolation.level,
    shouldCast: shouldCastImmolation,
    execute: executeImmolation,
  },
  'Insect Plague': {
    name: 'Insect Plague',
    level: metadataInsectPlague.level,
    shouldCast: shouldCastInsectPlague,
    execute: executeInsectPlague,
  },
  'Maelstrom': {
    name: 'Maelstrom',
    level: metadataMaelstrom.level,
    shouldCast: shouldCastMaelstrom,
    execute: executeMaelstrom,
  },
  'Mass Cure Wounds': {
    name: 'Mass Cure Wounds',
    level: metadataMassCureWounds.level,
    shouldCast: shouldCastMassCureWounds,
    execute: executeMassCureWounds,
  },
  'Mislead': {
    name: 'Mislead',
    level: metadataMislead.level,
    shouldCast: shouldCastMislead,
    execute: executeMislead,
  },
  'Modify Memory': {
    name: 'Modify Memory',
    level: metadataModifyMemory.level,
    shouldCast: shouldCastModifyMemory,
    execute: executeModifyMemory,
  },
  'Negative Energy Flood': {
    name: 'Negative Energy Flood',
    level: metadataNegativeEnergyFlood.level,
    shouldCast: shouldCastNegativeEnergyFlood,
    execute: executeNegativeEnergyFlood,
  },
  'Passwall': {
    name: 'Passwall',
    level: metadataPasswall.level,
    shouldCast: shouldCastPasswall,
    execute: executePasswall,
  },
  "Rary's Telepathic Bond": {
    name: "Rary's Telepathic Bond",
    level: metadataRarysTelepathicBond.level,
    shouldCast: shouldCastRarysTelepathicBond,
    execute: executeRarysTelepathicBond,
  },
  'Seeming': {
    name: 'Seeming',
    level: metadataSeeming.level,
    shouldCast: shouldCastSeeming,
    execute: executeSeeming,
  },
  'Skill Empowerment': {
    name: 'Skill Empowerment',
    level: metadataSkillEmpowerment.level,
    shouldCast: shouldCastSkillEmpowerment,
    execute: executeSkillEmpowerment,
  },
  "Songal's Elemental Suffusion": {
    name: "Songal's Elemental Suffusion",
    level: metadataSongalsElementalSuffusion.level,
    shouldCast: shouldCastSongalsElementalSuffusion,
    execute: executeSongalsElementalSuffusion,
  },
  'Steel Wind Strike': {
    name: 'Steel Wind Strike',
    level: metadataSteelWindStrike.level,
    shouldCast: shouldCastSteelWindStrike,
    execute: executeSteelWindStrike,
  },
  'Swift Quiver': {
    name: 'Swift Quiver',
    level: metadataSwiftQuiver.level,
    shouldCast: shouldCastSwiftQuiver,
    execute: executeSwiftQuiver,
  },
  'Synaptic Static': {
    name: 'Synaptic Static',
    level: metadataSynapticStatic.level,
    shouldCast: shouldCastSynapticStatic,
    execute: executeSynapticStatic,
  },
  'Telekinesis': {
    name: 'Telekinesis',
    level: metadataTelekinesis.level,
    shouldCast: shouldCastTelekinesis,
    execute: executeTelekinesis,
  },
  'Temporal Shunt': {
    name: 'Temporal Shunt',
    level: metadataTemporalShunt.level,
    shouldCast: shouldCastTemporalShunt,
    execute: executeTemporalShunt,
  },
  'Transmute Rock': {
    name: 'Transmute Rock',
    level: metadataTransmuteRock.level,
    shouldCast: shouldCastTransmuteRock,
    execute: executeTransmuteRock,
  },
  'Tree Stride': {
    name: 'Tree Stride',
    level: metadataTreeStride.level,
    shouldCast: shouldCastTreeStride,
    execute: executeTreeStride,
  },
  'Wrath of Nature': {
    name: 'Wrath of Nature',
    level: metadataWrathOfNature.level,
    shouldCast: shouldCastWrathOfNature,
    execute: executeWrathOfNature,
  },
  'Arcane Gate': {
    name: 'Arcane Gate',
    level: metadataArcaneGate.level,
    shouldCast: shouldCastArcaneGate,
    execute: executeArcaneGate,
  },
  'Blade Barrier': {
    name: 'Blade Barrier',
    level: metadataBladeBarrier.level,
    shouldCast: shouldCastBladeBarrier,
    execute: executeBladeBarrier,
  },
  'Bones of the Earth': {
    name: 'Bones of the Earth',
    level: metadataBonesOfTheEarth.level,
    shouldCast: shouldCastBonesOfTheEarth,
    execute: executeBonesOfTheEarth,
  },
  'Chain Lightning': {
    name: 'Chain Lightning',
    level: metadataChainLightning.level,
    shouldCast: shouldCastChainLightning,
    execute: executeChainLightning,
  },
  'Circle of Death': {
    name: 'Circle of Death',
    level: metadataCircleOfDeath.level,
    shouldCast: shouldCastCircleOfDeath,
    execute: executeCircleOfDeath,
  },
  'Create Homunculus': {
    name: 'Create Homunculus',
    level: metadataCreateHomunculus.level,
    shouldCast: shouldCastCreateHomunculus,
    execute: executeCreateHomunculus,
  },
  'Dirge': {
    name: 'Dirge',
    level: metadataDirge.level,
    shouldCast: shouldCastDirge,
    execute: executeDirge,
  },
  'Druid Grove': {
    name: 'Druid Grove',
    level: metadataDruidGrove.level,
    shouldCast: shouldCastDruidGrove,
    execute: executeDruidGrove,
  },
  "Elminster's Effulgent Spheres": {
    name: "Elminster's Effulgent Spheres",
    level: metadataElminstersEffulgentSpheres.level,
    shouldCast: shouldCastElminstersEffulgentSpheres,
    execute: executeElminstersEffulgentSpheres,
  },
  'Eyebite': {
    name: 'Eyebite',
    level: metadataEyebite.level,
    shouldCast: shouldCastEyebite,
    execute: executeEyebite,
  },
  "Fizban's Platinum Shield": {
    name: "Fizban's Platinum Shield",
    level: metadataFizbansPlatinumShield.level,
    shouldCast: shouldCastFizbansPlatinumShield,
    execute: executeFizbansPlatinumShield,
  },
  'Flesh to Stone': {
    name: 'Flesh to Stone',
    level: metadataFleshToStone.level,
    shouldCast: shouldCastFleshToStone,
    execute: executeFleshToStone,
  },
  'Globe of Invulnerability': {
    name: 'Globe of Invulnerability',
    level: metadataGlobeOfInvulnerability.level,
    shouldCast: shouldCastGlobeOfInvulnerability,
    execute: executeGlobeOfInvulnerability,
  },
  'Gravity Fissure': {
    name: 'Gravity Fissure',
    level: metadataGravityFissure.level,
    shouldCast: shouldCastGravityFissure,
    execute: executeGravityFissure,
  },
  'Heal': {
    name: 'Heal',
    level: metadataHeal.level,
    shouldCast: shouldCastHeal,
    execute: executeHeal,
  },
  'Investiture of Flame': {
    name: 'Investiture of Flame',
    level: metadataInvestitureOfFlame.level,
    shouldCast: shouldCastInvestitureOfFlame,
    execute: executeInvestitureOfFlame,
  },
  'Investiture of Ice': {
    name: 'Investiture of Ice',
    level: metadataInvestitureOfIce.level,
    shouldCast: shouldCastInvestitureOfIce,
    execute: executeInvestitureOfIce,
  },
  'Investiture of Stone': {
    name: 'Investiture of Stone',
    level: metadataInvestitureOfStone.level,
    shouldCast: shouldCastInvestitureOfStone,
    execute: executeInvestitureOfStone,
  },
  'Investiture of Wind': {
    name: 'Investiture of Wind',
    level: metadataInvestitureOfWind.level,
    shouldCast: shouldCastInvestitureOfWind,
    execute: executeInvestitureOfWind,
  },
  'Mass Suggestion': {
    name: 'Mass Suggestion',
    level: metadataMassSuggestion.level,
    shouldCast: shouldCastMassSuggestion,
    execute: executeMassSuggestion,
  },
  'Mental Prison': {
    name: 'Mental Prison',
    level: metadataMentalPrison.level,
    shouldCast: shouldCastMentalPrison,
    execute: executeMentalPrison,
  },
  'Move Earth': {
    name: 'Move Earth',
    level: metadataMoveEarth.level,
    shouldCast: shouldCastMoveEarth,
    execute: executeMoveEarth,
  },
  "Otiluke's Freezing Sphere": {
    name: "Otiluke's Freezing Sphere",
    level: metadataOtilukesFreezingSphere.level,
    shouldCast: shouldCastOtilukesFreezingSphere,
    execute: executeOtilukesFreezingSphere,
  },
  "Otto's Irresistible Dance": {
    name: "Otto's Irresistible Dance",
    level: metadataOttosIrresistibleDance.level,
    shouldCast: shouldCastOttosIrresistibleDance,
    execute: executeOttosIrresistibleDance,
  },
  'Primordial Ward': {
    name: 'Primordial Ward',
    level: metadataPrimordialWard.level,
    shouldCast: shouldCastPrimordialWard,
    execute: executePrimordialWard,
  },
  'Scatter': {
    name: 'Scatter',
    level: metadataScatter.level,
    shouldCast: shouldCastScatter,
    execute: executeScatter,
  },
  'Soul Cage': {
    name: 'Soul Cage',
    level: metadataSoulCage.level,
    shouldCast: shouldCastSoulCage,
    execute: executeSoulCage,
  },
  'Sunbeam': {
    name: 'Sunbeam',
    level: metadataSunbeam.level,
    shouldCast: shouldCastSunbeam,
    execute: executeSunbeam,
  },
  "Tasha's Otherworldly Guise": {
    name: "Tasha's Otherworldly Guise",
    level: metadataTashasOtherworldlyGuise.level,
    shouldCast: shouldCastTashasOtherworldlyGuise,
    execute: executeTashasOtherworldlyGuise,
  },
  "Tenser's Transformation": {
    name: "Tenser's Transformation",
    level: metadataTensersTransformation.level,
    shouldCast: shouldCastTensersTransformation,
    execute: executeTensersTransformation,
  },
  'Transport via Plants': {
    name: 'Transport via Plants',
    level: metadataTransportViaPlants.level,
    shouldCast: shouldCastTransportViaPlants,
    execute: executeTransportViaPlants,
  },
  'Crown of Stars': {
    name: 'Crown of Stars',
    level: metadataCrownOfStars.level,
    shouldCast: shouldCastCrownOfStars,
    execute: executeCrownOfStars,
  },
  'Delayed Blast Fireball': {
    name: 'Delayed Blast Fireball',
    level: metadataDelayedBlastFireball.level,
    shouldCast: shouldCastDelayedBlastFireball,
    execute: executeDelayedBlastFireball,
  },
  'Divine Word': {
    name: 'Divine Word',
    level: metadataDivineWord.level,
    shouldCast: shouldCastDivineWord,
    execute: executeDivineWord,
  },
  'Draconic Transformation': {
    name: 'Draconic Transformation',
    level: metadataDraconicTransformation.level,
    shouldCast: shouldCastDraconicTransformation,
    execute: executeDraconicTransformation,
  },
  'Fire Storm': {
    name: 'Fire Storm',
    level: metadataFireStorm.level,
    shouldCast: shouldCastFireStorm,
    execute: executeFireStorm,
  },
  'Forcecage': {
    name: 'Forcecage',
    level: metadataForcecage.level,
    shouldCast: shouldCastForcecage,
    execute: executeForcecage,
  },
  'Mirage Arcane': {
    name: 'Mirage Arcane',
    level: metadataMirageArcane.level,
    shouldCast: shouldCastMirageArcane,
    execute: executeMirageArcane,
  },
  "Mordenkainen's Magnificent Mansion": {
    name: "Mordenkainen's Magnificent Mansion",
    level: metadataMordenkainensMagnificentMansion.level,
    shouldCast: shouldCastMordenkainensMagnificentMansion,
    execute: executeMordenkainensMagnificentMansion,
  },
  "Mordenkainen's Sword": {
    name: "Mordenkainen's Sword",
    level: metadataMordenkainensSword.level,
    shouldCast: shouldCastMordenkainensSword,
    execute: executeMordenkainensSword,
  },
  'Power Word Pain': {
    name: 'Power Word Pain',
    level: metadataPowerWordPain.level,
    shouldCast: shouldCastPowerWordPain,
    execute: executePowerWordPain,
  },
  'Prismatic Spray': {
    name: 'Prismatic Spray',
    level: metadataPrismaticSpray.level,
    shouldCast: shouldCastPrismaticSpray,
    execute: executePrismaticSpray,
  },
  'Project Image': {
    name: 'Project Image',
    level: metadataProjectImage.level,
    shouldCast: shouldCastProjectImage,
    execute: executeProjectImage,
  },
  'Regenerate': {
    name: 'Regenerate',
    level: metadataRegenerate.level,
    shouldCast: shouldCastRegenerate,
    execute: executeRegenerate,
  },
  'Reverse Gravity': {
    name: 'Reverse Gravity',
    level: metadataReverseGravity.level,
    shouldCast: shouldCastReverseGravity,
    execute: executeReverseGravity,
  },
  'Sequester': {
    name: 'Sequester',
    level: metadataSequester.level,
    shouldCast: shouldCastSequester,
    execute: executeSequester,
  },
  "Simbul's Synostodweomer": {
    name: "Simbul's Synostodweomer",
    level: metadataSimbulsSynostodweomer.level,
    shouldCast: shouldCastSimbulsSynostodweomer,
    execute: executeSimbulsSynostodweomer,
  },
  'Tether Essence': {
    name: 'Tether Essence',
    level: metadataTetherEssence.level,
    shouldCast: shouldCastTetherEssence,
    execute: executeTetherEssence,
  },
  'Whirlwind': {
    name: 'Whirlwind',
    level: metadataWhirlwind.level,
    shouldCast: shouldCastWhirlwind,
    execute: executeWhirlwind,
  },
  "Abi-Dalzim's Horrid Wilting": {
    name: "Abi-Dalzim's Horrid Wilting",
    level: metadataAbiDalzimsHorridWilting.level,
    shouldCast: shouldCastAbiDalzimsHorridWilting,
    execute: executeAbiDalzimsHorridWilting,
  },
  'Animal Shapes': {
    name: 'Animal Shapes',
    level: metadataAnimalShapes.level,
    shouldCast: shouldCastAnimalShapes,
    execute: executeAnimalShapes,
  },
  'Antipathy/Sympathy': {
    name: 'Antipathy/Sympathy',
    level: metadataAntipathySympathy.level,
    shouldCast: shouldCastAntipathySympathy,
    execute: executeAntipathySympathy,
  },
  'Control Weather': {
    name: 'Control Weather',
    level: metadataControlWeather.level,
    shouldCast: shouldCastControlWeather,
    execute: executeControlWeather,
  },
  'Dark Star': {
    name: 'Dark Star',
    level: metadataDarkStar.level,
    shouldCast: shouldCastDarkStar,
    execute: executeDarkStar,
  },
  'Dominate Monster': {
    name: 'Dominate Monster',
    level: metadataDominateMonster.level,
    shouldCast: shouldCastDominateMonster,
    execute: executeDominateMonster,
  },
  'Earthquake': {
    name: 'Earthquake',
    level: metadataEarthquake.level,
    shouldCast: shouldCastEarthquake,
    execute: executeEarthquake,
  },
  'Feeblemind': {
    name: 'Feeblemind',
    level: metadataFeeblemind.level,
    shouldCast: shouldCastFeeblemind,
    execute: executeFeeblemind,
  },
  'Glibness': {
    name: 'Glibness',
    level: metadataGlibness.level,
    shouldCast: shouldCastGlibness,
    execute: executeGlibness,
  },
  'Holy Aura': {
    name: 'Holy Aura',
    level: metadataHolyAura.level,
    shouldCast: shouldCastHolyAura,
    execute: executeHolyAura,
  },
  'Holy Star of Mystra': {
    name: 'Holy Star of Mystra',
    level: metadataHolyStarOfMystra.level,
    shouldCast: shouldCastHolyStarOfMystra,
    execute: executeHolyStarOfMystra,
  },
  'Illusory Dragon': {
    name: 'Illusory Dragon',
    level: metadataIllusoryDragon.level,
    shouldCast: shouldCastIllusoryDragon,
    execute: executeIllusoryDragon,
  },
  'Incendiary Cloud': {
    name: 'Incendiary Cloud',
    level: metadataIncendiaryCloud.level,
    shouldCast: shouldCastIncendiaryCloud,
    execute: executeIncendiaryCloud,
  },
  'Maddening Darkness': {
    name: 'Maddening Darkness',
    level: metadataMaddeningDarkness.level,
    shouldCast: shouldCastMaddeningDarkness,
    execute: executeMaddeningDarkness,
  },
  'Power Word Stun': {
    name: 'Power Word Stun',
    level: metadataPowerWordStun.level,
    shouldCast: shouldCastPowerWordStun,
    execute: executePowerWordStun,
  },
  'Reality Break': {
    name: 'Reality Break',
    level: metadataRealityBreak.level,
    shouldCast: shouldCastRealityBreak,
    execute: executeRealityBreak,
  },
  'Tsunami': {
    name: 'Tsunami',
    level: metadataTsunami.level,
    shouldCast: shouldCastTsunami,
    execute: executeTsunami,
  },
  'Blade of Disaster': {
    name: 'Blade of Disaster',
    level: metadataBladeOfDisaster.level,
    shouldCast: shouldCastBladeOfDisaster,
    execute: executeBladeOfDisaster,
  },
  'Foresight': {
    name: 'Foresight',
    level: metadataForesight.level,
    shouldCast: shouldCastForesight,
    execute: executeForesight,
  },
  'Invulnerability': {
    name: 'Invulnerability',
    level: metadataInvulnerability.level,
    shouldCast: shouldCastInvulnerability,
    execute: executeInvulnerability,
  },
  'Mass Heal': {
    name: 'Mass Heal',
    level: metadataMassHeal.level,
    shouldCast: shouldCastMassHeal,
    execute: executeMassHeal,
  },
  'Mass Polymorph': {
    name: 'Mass Polymorph',
    level: metadataMassPolymorph.level,
    shouldCast: shouldCastMassPolymorph,
    execute: executeMassPolymorph,
  },
  'Meteor Swarm': {
    name: 'Meteor Swarm',
    level: metadataMeteorSwarm.level,
    shouldCast: shouldCastMeteorSwarm,
    execute: executeMeteorSwarm,
  },
  'Power Word Heal': {
    name: 'Power Word Heal',
    level: metadataPowerWordHeal.level,
    shouldCast: shouldCastPowerWordHeal,
    execute: executePowerWordHeal,
  },
  'Psychic Scream': {
    name: 'Psychic Scream',
    level: metadataPsychicScream.level,
    shouldCast: shouldCastPsychicScream,
    execute: executePsychicScream,
  },
  'Ravenous Void': {
    name: 'Ravenous Void',
    level: metadataRavenousVoid.level,
    shouldCast: shouldCastRavenousVoid,
    execute: executeRavenousVoid,
  },
  'Storm of Vengeance': {
    name: 'Storm of Vengeance',
    level: metadataStormOfVengeance.level,
    shouldCast: shouldCastStormOfVengeance,
    execute: executeStormOfVengeance,
  },
  'Time Ravage': {
    name: 'Time Ravage',
    level: metadataTimeRavage.level,
    shouldCast: shouldCastTimeRavage,
    execute: executeTimeRavage,
  },
  'Time Stop': {
    name: 'Time Stop',
    level: metadataTimeStop.level,
    shouldCast: shouldCastTimeStop,
    execute: executeTimeStop,
  },
  'Weird': {
    name: 'Weird',
    level: metadataWeird.level,
    shouldCast: shouldCastWeird,
    execute: executeWeird,
  },
};

// ---- Helper for planner: ordered list -----------------------

// Ordered by (level, name) — lowest level first, then alphabetical.
// The planner iterates this list and picks the first spell whose
// shouldCast returns true.
export const GENERIC_SPELL_LIST: GenericSpellDescriptor[] = Object.values(GENERIC_SPELLS);

// ---- Lookup helper ------------------------------------------

/**
 * Returns the GenericSpellDescriptor for the given canonical spell name,
 * or null if not found. Used by combat.ts's `case 'genericSpell':` branch.
 */
export function lookupGenericSpell(name: string): GenericSpellDescriptor | null {
  return GENERIC_SPELLS[name] ?? null;
}
